// GENERATED by tools/gen_ui.py from gearmulator's parameterDescriptions_mq.json.
// Do not edit; change the level tables in that script and regenerate.
#pragma once

namespace vavra {

// One synth parameter: the sysex index it is written at, and how the
// value shown on the knob maps to the byte on the wire
// (raw = shown * scale + offset).
struct MqParam { const char* key; uint16_t index; int8_t offset; uint8_t scale;
                 uint8_t rawMin, rawMax; };
static const MqParam g_mqParams[] = {
    {"aenv_attack", 211, 0, 1, 0, 127},
    {"aenv_attack_level", 212, 0, 1, 0, 127},
    {"aenv_decay", 213, 0, 1, 0, 127},
    {"aenv_decay2", 215, 0, 1, 0, 127},
    {"aenv_mode", 208, 0, 1, 0, 4},
    {"aenv_release", 217, 0, 1, 0, 127},
    {"aenv_sustain", 214, 0, 1, 0, 127},
    {"aenv_sustain2", 216, 0, 1, 0, 127},
    {"amp_mod_amount", 124, 64, 1, 0, 127},
    {"amp_mod_source", 123, 0, 1, 0, 13},
    {"amp_velocity", 122, 64, 1, 0, 127},
    {"amp_volume", 121, 0, 1, 0, 127},
    {"arp_clock", 314, 0, 1, 0, 127},
    {"arp_direction", 317, 0, 1, 0, 3},
    {"arp_length", 315, 0, 1, 0, 127},
    {"arp_max_notes", 313, 0, 1, 0, 15},
    {"arp_mode", 311, 0, 1, 0, 3},
    {"arp_octave_range", 316, 0, 1, 0, 9},
    {"arp_pattern", 312, 0, 1, 0, 16},
    {"arp_pattern_length", 323, 0, 1, 0, 15},
    {"arp_pattern_reset", 322, 0, 1, 0, 1},
    {"arp_same_note_overlap", 321, 0, 1, 0, 1},
    {"arp_sort_order", 318, 0, 1, 0, 5},
    {"arp_t_factor", 320, 0, 1, 0, 127},
    {"arp_velo_mode", 319, 0, 1, 0, 2},
    {"env3_attack", 223, 0, 1, 0, 127},
    {"env3_attack_level", 224, 0, 1, 0, 127},
    {"env3_decay", 225, 0, 1, 0, 127},
    {"env3_decay2", 227, 0, 1, 0, 127},
    {"env3_mode", 220, 0, 1, 0, 4},
    {"env3_release", 229, 0, 1, 0, 127},
    {"env3_sustain", 226, 0, 1, 0, 127},
    {"env3_sustain2", 228, 0, 1, 0, 127},
    {"env4_attack", 235, 0, 1, 0, 127},
    {"env4_attack_level", 236, 0, 1, 0, 127},
    {"env4_decay", 237, 0, 1, 0, 127},
    {"env4_decay2", 239, 0, 1, 0, 127},
    {"env4_mode", 232, 0, 1, 0, 4},
    {"env4_release", 241, 0, 1, 0, 127},
    {"env4_sustain", 238, 0, 1, 0, 127},
    {"env4_sustain2", 240, 0, 1, 0, 127},
    {"fenv_attack", 199, 0, 1, 0, 127},
    {"fenv_attack_level", 200, 0, 1, 0, 127},
    {"fenv_decay", 201, 0, 1, 0, 127},
    {"fenv_decay2", 203, 0, 1, 0, 127},
    {"fenv_mode", 196, 0, 1, 0, 4},
    {"fenv_release", 205, 0, 1, 0, 127},
    {"fenv_sustain", 202, 0, 1, 0, 127},
    {"fenv_sustain2", 204, 0, 1, 0, 127},
    {"flt1_cutoff", 78, 0, 1, 0, 127},
    {"flt1_cutoff_mod", 90, 64, 1, 0, 127},
    {"flt1_drive", 81, 0, 1, 0, 127},
    {"flt1_env_mod", 87, 64, 1, 0, 127},
    {"flt1_fm_amount", 92, 0, 1, 0, 127},
    {"flt1_fm_source", 91, 0, 1, 0, 11},
    {"flt1_key_track", 86, 64, 1, 0, 127},
    {"flt1_mod_source", 89, 0, 1, 0, 13},
    {"flt1_pan", 93, 64, 1, 0, 127},
    {"flt1_pan_mod", 95, 64, 1, 0, 127},
    {"flt1_pan_mod_source", 94, 0, 1, 0, 13},
    {"flt1_resonance", 80, 0, 1, 0, 127},
    {"flt1_type", 77, 0, 1, 0, 10},
    {"flt1_vel_mod", 88, 64, 1, 0, 127},
    {"flt2_cutoff", 98, 0, 1, 0, 127},
    {"flt2_cutoff_mod", 110, 64, 1, 0, 127},
    {"flt2_drive", 101, 0, 1, 0, 127},
    {"flt2_env_mod", 107, 64, 1, 0, 127},
    {"flt2_fm_amount", 112, 0, 1, 0, 127},
    {"flt2_fm_source", 111, 0, 1, 0, 11},
    {"flt2_key_track", 106, 64, 1, 0, 127},
    {"flt2_mod_source", 109, 0, 1, 0, 13},
    {"flt2_pan", 113, 64, 1, 0, 127},
    {"flt2_pan_mod", 115, 64, 1, 0, 127},
    {"flt2_pan_mod_source", 114, 0, 1, 0, 13},
    {"flt2_resonance", 100, 0, 1, 0, 127},
    {"flt2_type", 97, 0, 1, 0, 10},
    {"flt2_vel_mod", 108, 64, 1, 0, 127},
    {"fmod1_amount", 263, 64, 1, 0, 127},
    {"fmod1_destination", 262, 0, 1, 0, 30},
    {"fmod1_source", 261, 0, 1, 0, 13},
    {"fmod2_amount", 266, 64, 1, 0, 127},
    {"fmod2_destination", 265, 0, 1, 0, 30},
    {"fmod2_source", 264, 0, 1, 0, 13},
    {"fmod3_amount", 269, 64, 1, 0, 127},
    {"fmod3_destination", 268, 0, 1, 0, 30},
    {"fmod3_source", 267, 0, 1, 0, 13},
    {"fmod4_amount", 272, 64, 1, 0, 127},
    {"fmod4_destination", 271, 0, 1, 0, 30},
    {"fmod4_source", 270, 0, 1, 0, 13},
    {"fx1_chorus_delay", 133, 0, 1, 0, 127},
    {"fx1_chorus_depth", 131, 0, 1, 0, 127},
    {"fx1_chorus_speed", 130, 0, 1, 0, 127},
    {"fx1_flanger_depth", 131, 0, 1, 0, 127},
    {"fx1_flanger_feedback", 134, 0, 1, 0, 127},
    {"fx1_flanger_polarity", 138, 0, 1, 0, 1},
    {"fx1_flanger_speed", 130, 0, 1, 0, 127},
    {"fx1_mix", 129, 0, 1, 0, 127},
    {"fx1_overdrive_cutoff", 135, 0, 1, 0, 127},
    {"fx1_overdrive_drive", 131, 0, 1, 0, 127},
    {"fx1_overdrive_post_gain", 132, 0, 1, 0, 127},
    {"fx1_phaser_center", 135, 0, 1, 0, 127},
    {"fx1_phaser_depth", 131, 0, 1, 0, 127},
    {"fx1_phaser_feedback", 134, 0, 1, 0, 127},
    {"fx1_phaser_polarity", 138, 0, 1, 0, 1},
    {"fx1_phaser_spacing", 136, 0, 1, 0, 127},
    {"fx1_phaser_speed", 130, 0, 1, 0, 127},
    {"fx1_type", 128, 0, 1, 0, 6},
    {"fx1_vocoder_analysis_freq_high", 133, 0, 1, 0, 127},
    {"fx1_vocoder_analysis_freq_low", 132, 0, 1, 0, 127},
    {"fx1_vocoder_analysis_signal", 131, 0, 1, 0, 8},
    {"fx1_vocoder_attack", 138, 0, 1, 0, 127},
    {"fx1_vocoder_bands", 130, 0, 1, 2, 25},
    {"fx1_vocoder_bandwidth", 136, 0, 1, 0, 127},
    {"fx1_vocoder_decay", 139, 0, 1, 0, 127},
    {"fx1_vocoder_eq_band_mid", 141, 0, 1, 0, 24},
    {"fx1_vocoder_eq_level_high", 143, 0, 1, 0, 127},
    {"fx1_vocoder_eq_level_low", 140, 0, 1, 0, 127},
    {"fx1_vocoder_eq_level_mid", 142, 0, 1, 0, 127},
    {"fx1_vocoder_offset_hi", 135, 0, 1, 0, 127},
    {"fx1_vocoder_offset_s", 134, 0, 1, 0, 127},
    {"fx1_vocoder_resonance", 137, 0, 1, 0, 127},
    {"fx2_chorus_delay", 149, 0, 1, 0, 127},
    {"fx2_chorus_depth", 147, 0, 1, 0, 127},
    {"fx2_chorus_speed", 146, 0, 1, 0, 127},
    {"fx2_delay_autopan", 155, 0, 1, 0, 1},
    {"fx2_delay_cutoff", 151, 0, 1, 0, 127},
    {"fx2_delay_feedback", 150, 0, 1, 0, 127},
    {"fx2_delay_polarity", 154, 0, 1, 0, 1},
    {"fx2_flanger_depth", 147, 0, 1, 0, 127},
    {"fx2_flanger_feedback", 150, 0, 1, 0, 127},
    {"fx2_flanger_polarity", 154, 0, 1, 0, 1},
    {"fx2_flanger_speed", 146, 0, 1, 0, 127},
    {"fx2_mix", 145, 0, 1, 0, 127},
    {"fx2_overdrive_cutoff", 151, 0, 1, 0, 127},
    {"fx2_overdrive_drive", 147, 0, 1, 0, 127},
    {"fx2_overdrive_post_gain", 148, 0, 1, 0, 127},
    {"fx2_phaser_center", 151, 0, 1, 0, 127},
    {"fx2_phaser_depth", 147, 0, 1, 0, 127},
    {"fx2_phaser_feedback", 150, 0, 1, 0, 127},
    {"fx2_phaser_polarity", 154, 0, 1, 0, 1},
    {"fx2_phaser_spacing", 152, 0, 1, 0, 127},
    {"fx2_phaser_speed", 146, 0, 1, 0, 127},
    {"fx2_reverb_damping", 154, 0, 1, 0, 127},
    {"fx2_reverb_decay", 148, 0, 1, 0, 127},
    {"fx2_reverb_diffusion", 153, 0, 1, 0, 127},
    {"fx2_reverb_highpass", 152, 0, 1, 0, 127},
    {"fx2_reverb_lowpass", 151, 0, 1, 0, 127},
    {"fx2_reverb_pre_delay", 149, 0, 1, 0, 127},
    {"fx2_reverb_shape", 147, 0, 1, 0, 127},
    {"fx2_reverb_size", 146, 0, 1, 0, 127},
    {"fx2_type", 144, 0, 1, 0, 10},
    {"fx2_vocoder_analysis_freq_high", 149, 0, 1, 0, 127},
    {"fx2_vocoder_analysis_freq_low", 148, 0, 1, 0, 127},
    {"fx2_vocoder_analysis_signal", 147, 0, 1, 0, 8},
    {"fx2_vocoder_attack", 154, 0, 1, 0, 127},
    {"fx2_vocoder_bands", 146, 0, 1, 2, 25},
    {"fx2_vocoder_bandwidth", 152, 0, 1, 0, 127},
    {"fx2_vocoder_decay", 155, 0, 1, 0, 127},
    {"fx2_vocoder_eq_band_mid", 157, 0, 1, 0, 24},
    {"fx2_vocoder_eq_level_high", 159, 0, 1, 0, 127},
    {"fx2_vocoder_eq_level_low", 156, 0, 1, 0, 127},
    {"fx2_vocoder_eq_level_mid", 158, 0, 1, 0, 127},
    {"fx2_vocoder_offset_hi", 151, 0, 1, 0, 127},
    {"fx2_vocoder_offset_s", 150, 0, 1, 0, 127},
    {"fx2_vocoder_resonance", 153, 0, 1, 0, 127},
    {"glide_mode", 56, 0, 1, 0, 4},
    {"glide_rate", 57, 0, 1, 0, 127},
    {"lfo1_clocked", 164, 0, 1, 0, 1},
    {"lfo1_delay", 166, 0, 1, 0, 127},
    {"lfo1_fade", 167, 64, 1, 0, 127},
    {"lfo1_key_track", 170, 64, 1, 0, 127},
    {"lfo1_shape", 160, 0, 1, 0, 5},
    {"lfo1_speed", 161, 0, 1, 0, 127},
    {"lfo1_speed_clocked", 161, 0, 1, 0, 127},
    {"lfo1_start_phase", 165, 0, 1, 0, 127},
    {"lfo1_sync", 163, 0, 1, 0, 1},
    {"lfo2_clocked", 176, 0, 1, 0, 1},
    {"lfo2_delay", 178, 0, 1, 0, 127},
    {"lfo2_fade", 179, 64, 1, 0, 127},
    {"lfo2_key_track", 182, 64, 1, 0, 127},
    {"lfo2_shape", 172, 0, 1, 0, 5},
    {"lfo2_speed", 173, 0, 1, 0, 127},
    {"lfo2_speed_clocked", 173, 0, 1, 0, 127},
    {"lfo2_start_phase", 177, 0, 1, 0, 127},
    {"lfo2_sync", 175, 0, 1, 0, 1},
    {"lfo3_clocked", 188, 0, 1, 0, 1},
    {"lfo3_delay", 190, 0, 1, 0, 127},
    {"lfo3_fade", 191, 64, 1, 0, 127},
    {"lfo3_key_track", 194, 64, 1, 0, 127},
    {"lfo3_shape", 184, 0, 1, 0, 5},
    {"lfo3_speed", 185, 0, 1, 0, 127},
    {"lfo3_speed_clocked", 185, 0, 1, 0, 127},
    {"lfo3_start_phase", 189, 0, 1, 0, 127},
    {"lfo3_sync", 187, 0, 1, 0, 1},
    {"modif1_constant", 248, 0, 1, 0, 127},
    {"modif1_operator", 247, 0, 1, 0, 7},
    {"modif1_source1", 245, 0, 1, 0, 39},
    {"modif1_source2", 246, 0, 1, 0, 39},
    {"modif2_constant", 252, 0, 1, 0, 127},
    {"modif2_operator", 251, 0, 1, 0, 7},
    {"modif2_source1", 249, 0, 1, 0, 39},
    {"modif2_source2", 250, 0, 1, 0, 39},
    {"modif3_constant", 256, 0, 1, 0, 127},
    {"modif3_operator", 255, 0, 1, 0, 7},
    {"modif3_source1", 253, 0, 1, 0, 39},
    {"modif3_source2", 254, 0, 1, 0, 39},
    {"modif4_constant", 260, 0, 1, 0, 127},
    {"modif4_operator", 259, 0, 1, 0, 7},
    {"modif4_source1", 257, 0, 1, 0, 39},
    {"modif4_source2", 258, 0, 1, 0, 39},
    {"noise_balance", 68, 0, 1, 0, 127},
    {"noise_level", 67, 0, 1, 0, 127},
    {"noise_mode_f1", 75, 0, 1, 0, 3},
    {"noise_mode_f2", 76, 0, 1, 0, 3},
    {"osc1_balance", 62, 0, 1, 0, 127},
    {"osc1_bend_range", 4, 64, 1, 40, 88},
    {"osc1_detune", 3, 64, 1, 0, 127},
    {"osc1_fm_amount", 7, 0, 1, 0, 127},
    {"osc1_fm_source", 6, 0, 1, 0, 11},
    {"osc1_key_track", 5, 0, 1, 0, 127},
    {"osc1_level", 61, 0, 1, 0, 127},
    {"osc1_octave", 1, 64, 12, 16, 112},
    {"osc1_pulse_width", 9, 0, 1, 0, 127},
    {"osc1_pwm", 11, 64, 1, 0, 127},
    {"osc1_pwm_source", 10, 0, 1, 0, 13},
    {"osc1_semi", 2, 64, 1, 52, 76},
    {"osc1_shape", 8, 0, 1, 0, 6},
    {"osc1_sub_freq_div", 12, 0, 1, 0, 31},
    {"osc1_sub_volume", 13, 0, 1, 0, 31},
    {"osc2_balance", 64, 0, 1, 0, 127},
    {"osc2_bend_range", 20, 64, 1, 40, 88},
    {"osc2_detune", 19, 64, 1, 0, 127},
    {"osc2_fm_amount", 23, 0, 1, 0, 127},
    {"osc2_fm_source", 22, 0, 1, 0, 11},
    {"osc2_key_track", 21, 0, 1, 0, 127},
    {"osc2_level", 63, 0, 1, 0, 127},
    {"osc2_octave", 17, 64, 12, 16, 112},
    {"osc2_pulse_width", 25, 0, 1, 0, 127},
    {"osc2_pwm", 27, 64, 1, 0, 127},
    {"osc2_pwm_source", 26, 0, 1, 0, 13},
    {"osc2_semi", 18, 64, 1, 52, 76},
    {"osc2_shape", 24, 0, 1, 0, 6},
    {"osc2_sub_freq_div", 28, 0, 1, 0, 31},
    {"osc2_sub_volume", 29, 0, 1, 0, 31},
    {"osc3_balance", 66, 0, 1, 0, 127},
    {"osc3_bend_range", 36, 64, 1, 40, 88},
    {"osc3_detune", 35, 64, 1, 0, 127},
    {"osc3_fm_amount", 39, 0, 1, 0, 127},
    {"osc3_fm_source", 38, 0, 1, 0, 11},
    {"osc3_key_track", 37, 0, 1, 0, 127},
    {"osc3_level", 65, 0, 1, 0, 127},
    {"osc3_octave", 33, 64, 12, 16, 112},
    {"osc3_pulse_width", 41, 0, 1, 0, 127},
    {"osc3_pwm", 43, 64, 1, 0, 127},
    {"osc3_pwm_source", 42, 0, 1, 0, 13},
    {"osc3_semi", 34, 64, 1, 52, 76},
    {"osc3_shape", 40, 0, 1, 0, 4},
    {"pitchmod_amount", 51, 64, 1, 0, 127},
    {"pitchmod_src", 50, 0, 1, 0, 13},
    {"ringmod_balance", 72, 0, 1, 0, 127},
    {"ringmod_level", 71, 0, 1, 0, 127},
    {"smod1_amount", 287, 64, 1, 0, 127},
    {"smod1_destination", 286, 0, 1, 0, 57},
    {"smod1_source", 285, 0, 1, 0, 39},
    {"smod2_amount", 290, 64, 1, 0, 127},
    {"smod2_destination", 289, 0, 1, 0, 57},
    {"smod2_source", 288, 0, 1, 0, 39},
    {"smod3_amount", 293, 64, 1, 0, 127},
    {"smod3_destination", 292, 0, 1, 0, 57},
    {"smod3_source", 291, 0, 1, 0, 39},
    {"smod4_amount", 296, 64, 1, 0, 127},
    {"smod4_destination", 295, 0, 1, 0, 57},
    {"smod4_source", 294, 0, 1, 0, 39},
    {"sync", 49, 0, 1, 0, 1},
    {"tempo", 326, 0, 1, 0, 127},
    {"unison_count", 58, 0, 1, 0, 5},
    {"unison_detune", 59, 0, 1, 0, 127},
    {"voice_mode", 58, 0, 1, 0, 1},
};

static const char g_chainParamsHead[] =
    "{\"key\":\"preset\",\"name\":\"Preset\",";

static const char g_chainParamsPresetTail[] =
    "\"type\":\"enum\",\"default\":0}";

static const char g_chainParamsRest[] =
    "{\"key\":\"mode\",\"name\":\"Mode\",\"type\":\"enum\",\"options\":[\"Single\",\"Multi\"],\"default\":0},{\"key\":\"part\",\"n"
    "ame\":\"Part\",\"type\":\"int\",\"min\":1,\"max\":16,\"default\":1,\"visible_if\":{\"key\":\"mode\",\"equals\":1}},{\"key\""
    ":\"part_channel\",\"name\":\"Part Channel\",\"short_name\":\"PCHAN\",\"type\":\"int\",\"min\":0,\"max\":16,\"default\":0"
    ",\"visible_if\":{\"key\":\"mode\",\"equals\":1}},{\"key\":\"part_volume\",\"name\":\"Part Volume\",\"short_name\":\"PVO"
    "L\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127,\"visible_if\":{\"key\":\"mode\",\"equals\":1}},{\"key\":\"dsp_"
    "clock\",\"name\":\"DSP Clock\",\"short_name\":\"CLOCK\",\"type\":\"int\",\"min\":25,\"max\":100,\"default\":50,\"unit\":\""
    "%\"},{\"key\":\"gain\",\"name\":\"Gain\",\"type\":\"int\",\"min\":0,\"max\":100,\"default\":70},{\"key\":\"buffer_ms\",\"nam"
    "e\":\"Buffer\",\"short_name\":\"BUF\",\"type\":\"int\",\"min\":11,\"max\":139,\"default\":17,\"unit\":\"ms\"},{\"key\":\"osc"
    "1_shape\",\"name\":\"Shape\",\"short_name\":\"SHAPE\",\"type\":\"enum\",\"options\":[\"Off\",\"Pulse\",\"Saw\",\"Triangle\""
    ",\"Sine\",\"Alt 1\",\"Alt 2\"]},{\"key\":\"osc1_octave\",\"name\":\"Octave\",\"short_name\":\"OCT\",\"type\":\"int\",\"min\""
    ":-4,\"max\":4},{\"key\":\"osc1_semi\",\"name\":\"Semi\",\"short_name\":\"SEMI\",\"type\":\"enum\",\"options\":[\"-64\",\"-6"
    "3\",\"-62\",\"-61\",\"-60\",\"-59\",\"-58\",\"-57\",\"-56\",\"-55\",\"-54\",\"-53\",\"-52\",\"-51\",\"-50\",\"-49\",\"-48\",\"-47\",\""
    "-46\",\"-45\",\"-44\",\"-43\",\"-42\",\"-41\",\"-40\"]},{\"key\":\"osc1_detune\",\"name\":\"Detune\",\"short_name\":\"DTUNE\""
    ",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"osc1_pulse_width\",\"name\":\"Pulse Width\",\"short_name\":\"PW\",\""
    "type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"osc1_pwm\",\"name\":\"PWM\",\"short_name\":\"PWM\",\"type"
    "\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"osc1_pwm_source\",\"name\":\"PWM Source\",\"short_name\":\"PWSRC\",\"type\""
    ":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"E"
    "nv 3\",\"Env 4\",\"Velocity\",\"Modwheel\",\"Pitch Bend\",\"Aftertouch\"]},{\"key\":\"osc1_key_track\",\"name\":\"Keyt"
    "rack\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":96},{\"key\":\"osc1_bend_range\",\"name\":\"Bend\",\"type\":\"in"
    "t\",\"min\":-24,\"max\":24},{\"key\":\"osc1_fm_source\",\"name\":\"FM Source\",\"short_name\":\"FMSRC\",\"type\":\"enum\""
    ",\"options\":[\"Off\",\"Osc 1\",\"Osc 2\",\"Osc 3\",\"Noise\",\"LFO 1\",\"LFO 2\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"En"
    "v 3\",\"Env 4\"]},{\"key\":\"osc1_fm_amount\",\"name\":\"FM Amt\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"osc1_"
    "sub_freq_div\",\"name\":\"Sub Div\",\"type\":\"enum\",\"options\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\""
    ",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\""
    ",\"31\"]},{\"key\":\"osc1_sub_volume\",\"name\":\"Sub Volume\",\"short_name\":\"SUBVL\",\"type\":\"int\",\"min\":0,\"max\""
    ":31},{\"key\":\"osc2_shape\",\"name\":\"Shape\",\"short_name\":\"SHAPE\",\"type\":\"enum\",\"options\":[\"Off\",\"Pulse\","
    "\"Saw\",\"Triangle\",\"Sine\",\"Alt 1\",\"Alt 2\"]},{\"key\":\"osc2_octave\",\"name\":\"Octave\",\"short_name\":\"OCT\",\"t"
    "ype\":\"int\",\"min\":-4,\"max\":4},{\"key\":\"osc2_semi\",\"name\":\"Semi\",\"short_name\":\"SEMI\",\"type\":\"enum\",\"opt"
    "ions\":[\"-64\",\"-63\",\"-62\",\"-61\",\"-60\",\"-59\",\"-58\",\"-57\",\"-56\",\"-55\",\"-54\",\"-53\",\"-52\",\"-51\",\"-50\",\"-4"
    "9\",\"-48\",\"-47\",\"-46\",\"-45\",\"-44\",\"-43\",\"-42\",\"-41\",\"-40\"]},{\"key\":\"osc2_detune\",\"name\":\"Detune\",\"sho"
    "rt_name\":\"DTUNE\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"osc2_pulse_width\",\"name\":\"Pulse Width\",\"sh"
    "ort_name\":\"PW\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"osc2_pwm\",\"name\":\"PWM\",\"short_n"
    "ame\":\"PWM\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"osc2_pwm_source\",\"name\":\"PWM Source\",\"short_name"
    "\":\"PWSRC\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter E"
    "nv\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Velocity\",\"Modwheel\",\"Pitch Bend\",\"Aftertouch\"]},{\"key\":\"osc2_key_tra"
    "ck\",\"name\":\"Keytrack\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":96},{\"key\":\"osc2_bend_range\",\"name\":\""
    "Bend\",\"type\":\"int\",\"min\":-24,\"max\":24},{\"key\":\"osc2_fm_source\",\"name\":\"FM Source\",\"short_name\":\"FMSR"
    "C\",\"type\":\"enum\",\"options\":[\"Off\",\"Osc 1\",\"Osc 2\",\"Osc 3\",\"Noise\",\"LFO 1\",\"LFO 2\",\"LFO 3\",\"Filter En"
    "v\",\"Amp Env\",\"Env 3\",\"Env 4\"]},{\"key\":\"osc2_fm_amount\",\"name\":\"FM Amt\",\"type\":\"int\",\"min\":0,\"max\":12"
    "7},{\"key\":\"osc2_sub_freq_div\",\"name\":\"Sub Div\",\"type\":\"enum\",\"options\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\","
    "\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27"
    "\",\"28\",\"29\",\"30\",\"31\"]},{\"key\":\"osc2_sub_volume\",\"name\":\"Sub Volume\",\"short_name\":\"SUBVL\",\"type\":\"in"
    "t\",\"min\":0,\"max\":31},{\"key\":\"osc3_shape\",\"name\":\"Shape\",\"short_name\":\"SHAPE\",\"type\":\"enum\",\"options\""
    ":[\"Off\",\"Pulse\",\"Saw\",\"Triangle\",\"Sine\"]},{\"key\":\"osc3_octave\",\"name\":\"Octave\",\"short_name\":\"OCT\",\"t"
    "ype\":\"int\",\"min\":-4,\"max\":4},{\"key\":\"osc3_semi\",\"name\":\"Semi\",\"short_name\":\"SEMI\",\"type\":\"enum\",\"opt"
    "ions\":[\"-64\",\"-63\",\"-62\",\"-61\",\"-60\",\"-59\",\"-58\",\"-57\",\"-56\",\"-55\",\"-54\",\"-53\",\"-52\",\"-51\",\"-50\",\"-4"
    "9\",\"-48\",\"-47\",\"-46\",\"-45\",\"-44\",\"-43\",\"-42\",\"-41\",\"-40\"]},{\"key\":\"osc3_detune\",\"name\":\"Detune\",\"sho"
    "rt_name\":\"DTUNE\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"osc3_pulse_width\",\"name\":\"Pulse Width\",\"sh"
    "ort_name\":\"PW\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"osc3_pwm\",\"name\":\"PWM\",\"short_n"
    "ame\":\"PWM\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"osc3_pwm_source\",\"name\":\"PWM Source\",\"short_name"
    "\":\"PWSRC\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter E"
    "nv\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Velocity\",\"Modwheel\",\"Pitch Bend\",\"Aftertouch\"]},{\"key\":\"osc3_key_tra"
    "ck\",\"name\":\"Keytrack\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":96},{\"key\":\"osc3_bend_range\",\"name\":\""
    "Bend\",\"type\":\"int\",\"min\":-24,\"max\":24},{\"key\":\"osc3_fm_source\",\"name\":\"FM Source\",\"short_name\":\"FMSR"
    "C\",\"type\":\"enum\",\"options\":[\"Off\",\"Osc 1\",\"Osc 2\",\"Osc 3\",\"Noise\",\"LFO 1\",\"LFO 2\",\"LFO 3\",\"Filter En"
    "v\",\"Amp Env\",\"Env 3\",\"Env 4\"]},{\"key\":\"osc3_fm_amount\",\"name\":\"FM Amt\",\"type\":\"int\",\"min\":0,\"max\":12"
    "7},{\"key\":\"osc1_level\",\"name\":\"Osc 1 Level\",\"short_name\":\"O1LVL\",\"type\":\"int\",\"min\":0,\"max\":127},{\"k"
    "ey\":\"osc1_balance\",\"name\":\"Osc 1 Balance\",\"short_name\":\"O1BAL\",\"type\":\"int\",\"min\":0,\"max\":127,\"defau"
    "lt\":64},{\"key\":\"osc2_level\",\"name\":\"Osc 2 Level\",\"short_name\":\"O2LVL\",\"type\":\"int\",\"min\":0,\"max\":127"
    "},{\"key\":\"osc2_balance\",\"name\":\"Osc 2 Balance\",\"short_name\":\"O2BAL\",\"type\":\"int\",\"min\":0,\"max\":127,\""
    "default\":64},{\"key\":\"osc3_level\",\"name\":\"Osc 3 Level\",\"short_name\":\"O3LVL\",\"type\":\"int\",\"min\":0,\"max"
    "\":127},{\"key\":\"osc3_balance\",\"name\":\"Osc 3 Balance\",\"short_name\":\"O3BAL\",\"type\":\"int\",\"min\":0,\"max\":"
    "127,\"default\":64},{\"key\":\"noise_level\",\"name\":\"Noise Level\",\"short_name\":\"NSLVL\",\"type\":\"int\",\"min\":"
    "0,\"max\":127},{\"key\":\"ringmod_level\",\"name\":\"Ring Mod Level\",\"short_name\":\"RMLVL\",\"type\":\"int\",\"min\":"
    "0,\"max\":127},{\"key\":\"noise_balance\",\"name\":\"Noise Balance\",\"short_name\":\"NSBAL\",\"type\":\"int\",\"min\":0"
    ",\"max\":127,\"default\":64},{\"key\":\"ringmod_balance\",\"name\":\"Ring Mod Balance\",\"short_name\":\"RMBAL\",\"ty"
    "pe\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"noise_mode_f1\",\"name\":\"Noise Mode F1\",\"type\":\"enum"
    "\",\"options\":[\"Noise\",\"Ext Left\",\"Ext Right\",\"Ext L+R\"],\"short_name\":\"NMDF1\"},{\"key\":\"noise_mode_f2\","
    "\"name\":\"Noise Mode F2\",\"type\":\"enum\",\"options\":[\"Noise\",\"Ext Left\",\"Ext Right\",\"Ext L+R\"],\"short_nam"
    "e\":\"NMDF2\"},{\"key\":\"flt1_type\",\"name\":\"Type\",\"short_name\":\"TYPE\",\"type\":\"enum\",\"options\":[\"Off\",\"24 "
    "dB LP\",\"12 dB LP\",\"24 dB BP\",\"12 dB BP\",\"24 dB HP\",\"12 dB HP\",\"24 dB Notch\",\"12 dB Notch\",\"Comb+\",\"C"
    "omb-\"]},{\"key\":\"flt1_cutoff\",\"name\":\"Cutoff\",\"short_name\":\"CUT\",\"type\":\"int\",\"min\":0,\"max\":127,\"defa"
    "ult\":127},{\"key\":\"flt1_resonance\",\"name\":\"Resonance\",\"short_name\":\"RES\",\"type\":\"int\",\"min\":0,\"max\":1"
    "27},{\"key\":\"flt1_drive\",\"name\":\"Drive\",\"short_name\":\"DRIVE\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\""
    "flt1_env_mod\",\"name\":\"Env Amt\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"flt1_key_track\",\"name\":\"Keyt"
    "rack\",\"type\":\"int\",\"min\":-64,\"max\":63,\"default\":0},{\"key\":\"flt1_vel_mod\",\"name\":\"Velocity\",\"type\":\"i"
    "nt\",\"min\":-64,\"max\":63},{\"key\":\"flt1_pan\",\"name\":\"Pan\",\"short_name\":\"PAN\",\"type\":\"int\",\"min\":-64,\"ma"
    "x\":63},{\"key\":\"flt1_mod_source\",\"name\":\"Mod Src\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\""
    ",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Velocity\",\"Modwheel\",\"Pitch Be"
    "nd\",\"Aftertouch\"]},{\"key\":\"flt1_cutoff_mod\",\"name\":\"Cut Mod\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\""
    ":\"flt1_fm_source\",\"name\":\"FM Source\",\"short_name\":\"FMSRC\",\"type\":\"enum\",\"options\":[\"Off\",\"Osc 1\",\"Os"
    "c 2\",\"Osc 3\",\"Noise\",\"LFO 1\",\"LFO 2\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\"]},{\"key\":\"flt1_f"
    "m_amount\",\"name\":\"FM Amt\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"flt1_pan_mod_source\",\"name\":\"Pan S"
    "rc\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"A"
    "mp Env\",\"Env 3\",\"Env 4\",\"Velocity\",\"Modwheel\",\"Pitch Bend\",\"Aftertouch\"]},{\"key\":\"flt1_pan_mod\",\"nam"
    "e\":\"Pan Mod\",\"short_name\":\"PNMOD\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"flt2_type\",\"name\":\"Type\","
    "\"short_name\":\"TYPE\",\"type\":\"enum\",\"options\":[\"Off\",\"24 dB LP\",\"12 dB LP\",\"24 dB BP\",\"12 dB BP\",\"24 d"
    "B HP\",\"12 dB HP\",\"24 dB Notch\",\"12 dB Notch\",\"Comb+\",\"Comb-\"]},{\"key\":\"flt2_cutoff\",\"name\":\"Cutoff\","
    "\"short_name\":\"CUT\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"flt2_resonance\",\"name\":\"Res"
    "onance\",\"short_name\":\"RES\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"flt2_drive\",\"name\":\"Drive\",\"short"
    "_name\":\"DRIVE\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"flt2_env_mod\",\"name\":\"Env Amt\",\"type\":\"int\",\""
    "min\":-64,\"max\":63},{\"key\":\"flt2_key_track\",\"name\":\"Keytrack\",\"type\":\"int\",\"min\":-64,\"max\":63,\"defaul"
    "t\":0},{\"key\":\"flt2_vel_mod\",\"name\":\"Velocity\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"flt2_pan\",\"na"
    "me\":\"Pan\",\"short_name\":\"PAN\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"flt2_mod_source\",\"name\":\"Mod S"
    "rc\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"A"
    "mp Env\",\"Env 3\",\"Env 4\",\"Velocity\",\"Modwheel\",\"Pitch Bend\",\"Aftertouch\"]},{\"key\":\"flt2_cutoff_mod\",\""
    "name\":\"Cut Mod\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"flt2_fm_source\",\"name\":\"FM Source\",\"short_n"
    "ame\":\"FMSRC\",\"type\":\"enum\",\"options\":[\"Off\",\"Osc 1\",\"Osc 2\",\"Osc 3\",\"Noise\",\"LFO 1\",\"LFO 2\",\"LFO 3\","
    "\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\"]},{\"key\":\"flt2_fm_amount\",\"name\":\"FM Amt\",\"type\":\"int\",\"min\":"
    "0,\"max\":127},{\"key\":\"flt2_pan_mod_source\",\"name\":\"Pan Src\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"L"
    "FO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Velocity\",\"Modwheel\""
    ",\"Pitch Bend\",\"Aftertouch\"]},{\"key\":\"flt2_pan_mod\",\"name\":\"Pan Mod\",\"short_name\":\"PNMOD\",\"type\":\"int"
    "\",\"min\":-64,\"max\":63},{\"key\":\"amp_volume\",\"name\":\"Volume\",\"short_name\":\"VOL\",\"type\":\"int\",\"min\":0,\"m"
    "ax\":127,\"default\":96},{\"key\":\"amp_velocity\",\"name\":\"Velocity\",\"short_name\":\"VEL\",\"type\":\"int\",\"min\":"
    "-64,\"max\":63},{\"key\":\"amp_mod_source\",\"name\":\"Mod Src\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1"
    " * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Velocity\",\"Modwheel\",\"Pi"
    "tch Bend\",\"Aftertouch\"]},{\"key\":\"amp_mod_amount\",\"name\":\"Mod Amount\",\"type\":\"int\",\"min\":-64,\"max\":63"
    "},{\"key\":\"fenv_attack\",\"name\":\"Attack\",\"short_name\":\"ATK\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"fe"
    "nv_decay\",\"name\":\"Decay\",\"short_name\":\"DEC\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"fenv_sustain\",\"n"
    "ame\":\"Sustain\",\"short_name\":\"SUS\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"fenv_release"
    "\",\"name\":\"Release\",\"short_name\":\"REL\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"fenv_attack_level\",\"na"
    "me\":\"Atk Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"fenv_decay2\",\"name\":\"Decay2\",\""
    "short_name\":\"DEC2\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"fenv_sustain2\",\"name\":\"Sustain2\",\"short_n"
    "ame\":\"SUS2\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"fenv_mode\",\"name\":\"Mode\",\"short_na"
    "me\":\"MODE\",\"type\":\"enum\",\"options\":[\"ADSR\",\"ADS1DS2R\",\"One Shot\",\"Loop S1S2\",\"Loop All\"]},{\"key\":\"ae"
    "nv_attack\",\"name\":\"Attack\",\"short_name\":\"ATK\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"aenv_decay\",\"n"
    "ame\":\"Decay\",\"short_name\":\"DEC\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"aenv_sustain\",\"name\":\"Sustai"
    "n\",\"short_name\":\"SUS\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"aenv_release\",\"name\":\"Re"
    "lease\",\"short_name\":\"REL\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"aenv_attack_level\",\"name\":\"Atk Lev"
    "el\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"aenv_decay2\",\"name\":\"Decay2\",\"short_name\":"
    "\"DEC2\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"aenv_sustain2\",\"name\":\"Sustain2\",\"short_name\":\"SUS2\","
    "\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"aenv_mode\",\"name\":\"Mode\",\"short_name\":\"MODE\",\""
    "type\":\"enum\",\"options\":[\"ADSR\",\"ADS1DS2R\",\"One Shot\",\"Loop S1S2\",\"Loop All\"]},{\"key\":\"env3_attack\",\""
    "name\":\"Attack\",\"short_name\":\"ATK\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"env3_decay\",\"name\":\"Decay\""
    ",\"short_name\":\"DEC\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"env3_sustain\",\"name\":\"Sustain\",\"short_na"
    "me\":\"SUS\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"env3_release\",\"name\":\"Release\",\"shor"
    "t_name\":\"REL\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"env3_attack_level\",\"name\":\"Atk Level\",\"type\":\""
    "int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"env3_decay2\",\"name\":\"Decay2\",\"short_name\":\"DEC2\",\"type"
    "\":\"int\",\"min\":0,\"max\":127},{\"key\":\"env3_sustain2\",\"name\":\"Sustain2\",\"short_name\":\"SUS2\",\"type\":\"int\""
    ",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"env3_mode\",\"name\":\"Mode\",\"short_name\":\"MODE\",\"type\":\"enum\""
    ",\"options\":[\"ADSR\",\"ADS1DS2R\",\"One Shot\",\"Loop S1S2\",\"Loop All\"]},{\"key\":\"env4_attack\",\"name\":\"Attac"
    "k\",\"short_name\":\"ATK\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"env4_decay\",\"name\":\"Decay\",\"short_name"
    "\":\"DEC\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"env4_sustain\",\"name\":\"Sustain\",\"short_name\":\"SUS\",\"t"
    "ype\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"env4_release\",\"name\":\"Release\",\"short_name\":\"REL"
    "\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"env4_attack_level\",\"name\":\"Atk Level\",\"type\":\"int\",\"min\":0"
    ",\"max\":127,\"default\":127},{\"key\":\"env4_decay2\",\"name\":\"Decay2\",\"short_name\":\"DEC2\",\"type\":\"int\",\"min"
    "\":0,\"max\":127},{\"key\":\"env4_sustain2\",\"name\":\"Sustain2\",\"short_name\":\"SUS2\",\"type\":\"int\",\"min\":0,\"ma"
    "x\":127,\"default\":127},{\"key\":\"env4_mode\",\"name\":\"Mode\",\"short_name\":\"MODE\",\"type\":\"enum\",\"options\":["
    "\"ADSR\",\"ADS1DS2R\",\"One Shot\",\"Loop S1S2\",\"Loop All\"]},{\"key\":\"lfo1_shape\",\"name\":\"Shape\",\"short_name"
    "\":\"SHAPE\",\"type\":\"enum\",\"options\":[\"Sine\",\"Triangle\",\"Square\",\"Saw\",\"Random\",\"S&H\"]},{\"key\":\"lfo1_sp"
    "eed\",\"name\":\"Speed\",\"short_name\":\"SPEED\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"visible_if\":{\""
    "key\":\"lfo1_clocked\",\"equals\":0}},{\"key\":\"lfo1_speed_clocked\",\"name\":\"Sync Speed\",\"type\":\"int\",\"min\":"
    "0,\"max\":127,\"default\":94,\"visible_if\":{\"key\":\"lfo1_clocked\",\"equals\":1}},{\"key\":\"lfo1_clocked\",\"name"
    "\":\"Clocked\",\"short_name\":\"CLOCK\",\"type\":\"int\",\"min\":0,\"max\":1},{\"key\":\"lfo1_sync\",\"name\":\"Sync\",\"sho"
    "rt_name\":\"SYNC\",\"type\":\"int\",\"min\":0,\"max\":1},{\"key\":\"lfo1_start_phase\",\"name\":\"Phase\",\"type\":\"int\","
    "\"min\":0,\"max\":127},{\"key\":\"lfo1_delay\",\"name\":\"Delay\",\"short_name\":\"DELAY\",\"type\":\"int\",\"min\":0,\"max"
    "\":127},{\"key\":\"lfo1_fade\",\"name\":\"Fade\",\"short_name\":\"FADE\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":"
    "\"lfo1_key_track\",\"name\":\"Keytrack\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"lfo2_shape\",\"name\":\"Shap"
    "e\",\"short_name\":\"SHAPE\",\"type\":\"enum\",\"options\":[\"Sine\",\"Triangle\",\"Square\",\"Saw\",\"Random\",\"S&H\"]},{"
    "\"key\":\"lfo2_speed\",\"name\":\"Speed\",\"short_name\":\"SPEED\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\""
    "visible_if\":{\"key\":\"lfo2_clocked\",\"equals\":0}},{\"key\":\"lfo2_speed_clocked\",\"name\":\"Sync Speed\",\"type"
    "\":\"int\",\"min\":0,\"max\":127,\"default\":94,\"visible_if\":{\"key\":\"lfo2_clocked\",\"equals\":1}},{\"key\":\"lfo2_"
    "clocked\",\"name\":\"Clocked\",\"short_name\":\"CLOCK\",\"type\":\"int\",\"min\":0,\"max\":1},{\"key\":\"lfo2_sync\",\"nam"
    "e\":\"Sync\",\"short_name\":\"SYNC\",\"type\":\"int\",\"min\":0,\"max\":1},{\"key\":\"lfo2_start_phase\",\"name\":\"Phase\""
    ",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"lfo2_delay\",\"name\":\"Delay\",\"short_name\":\"DELAY\",\"type\":\"int"
    "\",\"min\":0,\"max\":127},{\"key\":\"lfo2_fade\",\"name\":\"Fade\",\"short_name\":\"FADE\",\"type\":\"int\",\"min\":-64,\"ma"
    "x\":63},{\"key\":\"lfo2_key_track\",\"name\":\"Keytrack\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"lfo3_shape"
    "\",\"name\":\"Shape\",\"short_name\":\"SHAPE\",\"type\":\"enum\",\"options\":[\"Sine\",\"Triangle\",\"Square\",\"Saw\",\"Ran"
    "dom\",\"S&H\"]},{\"key\":\"lfo3_speed\",\"name\":\"Speed\",\"short_name\":\"SPEED\",\"type\":\"int\",\"min\":0,\"max\":127,"
    "\"default\":64,\"visible_if\":{\"key\":\"lfo3_clocked\",\"equals\":0}},{\"key\":\"lfo3_speed_clocked\",\"name\":\"Syn"
    "c Speed\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":94,\"visible_if\":{\"key\":\"lfo3_clocked\",\"equals\":1}}"
    ",{\"key\":\"lfo3_clocked\",\"name\":\"Clocked\",\"short_name\":\"CLOCK\",\"type\":\"int\",\"min\":0,\"max\":1},{\"key\":\"l"
    "fo3_sync\",\"name\":\"Sync\",\"short_name\":\"SYNC\",\"type\":\"int\",\"min\":0,\"max\":1},{\"key\":\"lfo3_start_phase\","
    "\"name\":\"Phase\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"lfo3_delay\",\"name\":\"Delay\",\"short_name\":\"DELA"
    "Y\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"lfo3_fade\",\"name\":\"Fade\",\"short_name\":\"FADE\",\"type\":\"int\""
    ",\"min\":-64,\"max\":63},{\"key\":\"lfo3_key_track\",\"name\":\"Keytrack\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"ke"
    "y\":\"fmod1_source\",\"name\":\"F1 Src\",\"short_name\":\"F1SRC\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1"
    " * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Velocity\",\"Modwheel\",\"Pi"
    "tch Bend\",\"Aftertouch\"]},{\"key\":\"fmod1_destination\",\"name\":\"F1 Dest\",\"short_name\":\"F1DST\",\"type\":\"en"
    "um\",\"options\":[\"Pitch\",\"O1 Pitch\",\"O1 FM\",\"O1 PW\",\"O2 Pitch\",\"O2 FM\",\"O2 PW\",\"O3 Pitch\",\"O3 FM\",\"O3 "
    "PW\",\"O1 Level\",\"O1 Balance\",\"O2 Level\",\"O2 Balance\",\"O3 Level\",\"O3 Balance\",\"Ring Level\",\"Ring Balan"
    "ce\",\"N/E Level\",\"N/E Balance\",\"F1 Cutoff\",\"F1 Resonance\",\"F1 FM\",\"F1 Drive\",\"F1 Pan\",\"F2 Cutoff\",\"F2"
    " Resonance\",\"F2 FM\",\"F2 Drive\",\"F2 Pan\",\"Volume\"]},{\"key\":\"fmod1_amount\",\"name\":\"F1 Amt\",\"short_name"
    "\":\"F1AMT\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"fmod2_source\",\"name\":\"F2 Src\",\"short_name\":\"F2SRC"
    "\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp"
    " Env\",\"Env 3\",\"Env 4\",\"Velocity\",\"Modwheel\",\"Pitch Bend\",\"Aftertouch\"]},{\"key\":\"fmod2_destination\",\""
    "name\":\"F2 Dest\",\"short_name\":\"F2DST\",\"type\":\"enum\",\"options\":[\"Pitch\",\"O1 Pitch\",\"O1 FM\",\"O1 PW\",\"O2"
    " Pitch\",\"O2 FM\",\"O2 PW\",\"O3 Pitch\",\"O3 FM\",\"O3 PW\",\"O1 Level\",\"O1 Balance\",\"O2 Level\",\"O2 Balance\",\""
    "O3 Level\",\"O3 Balance\",\"Ring Level\",\"Ring Balance\",\"N/E Level\",\"N/E Balance\",\"F1 Cutoff\",\"F1 Resonan"
    "ce\",\"F1 FM\",\"F1 Drive\",\"F1 Pan\",\"F2 Cutoff\",\"F2 Resonance\",\"F2 FM\",\"F2 Drive\",\"F2 Pan\",\"Volume\"]},{\""
    "key\":\"fmod2_amount\",\"name\":\"F2 Amt\",\"short_name\":\"F2AMT\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"fm"
    "od3_source\",\"name\":\"F3 Src\",\"short_name\":\"F3SRC\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\""
    ",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Velocity\",\"Modwheel\",\"Pitch Be"
    "nd\",\"Aftertouch\"]},{\"key\":\"fmod3_destination\",\"name\":\"F3 Dest\",\"short_name\":\"F3DST\",\"type\":\"enum\",\"o"
    "ptions\":[\"Pitch\",\"O1 Pitch\",\"O1 FM\",\"O1 PW\",\"O2 Pitch\",\"O2 FM\",\"O2 PW\",\"O3 Pitch\",\"O3 FM\",\"O3 PW\",\"O"
    "1 Level\",\"O1 Balance\",\"O2 Level\",\"O2 Balance\",\"O3 Level\",\"O3 Balance\",\"Ring Level\",\"Ring Balance\",\"N"
    "/E Level\",\"N/E Balance\",\"F1 Cutoff\",\"F1 Resonance\",\"F1 FM\",\"F1 Drive\",\"F1 Pan\",\"F2 Cutoff\",\"F2 Reson"
    "ance\",\"F2 FM\",\"F2 Drive\",\"F2 Pan\",\"Volume\"]},{\"key\":\"fmod3_amount\",\"name\":\"F3 Amt\",\"short_name\":\"F3A"
    "MT\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"fmod4_source\",\"name\":\"F4 Src\",\"short_name\":\"F4SRC\",\"typ"
    "e\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\","
    "\"Env 3\",\"Env 4\",\"Velocity\",\"Modwheel\",\"Pitch Bend\",\"Aftertouch\"]},{\"key\":\"fmod4_destination\",\"name\":"
    "\"F4 Dest\",\"short_name\":\"F4DST\",\"type\":\"enum\",\"options\":[\"Pitch\",\"O1 Pitch\",\"O1 FM\",\"O1 PW\",\"O2 Pitch"
    "\",\"O2 FM\",\"O2 PW\",\"O3 Pitch\",\"O3 FM\",\"O3 PW\",\"O1 Level\",\"O1 Balance\",\"O2 Level\",\"O2 Balance\",\"O3 Lev"
    "el\",\"O3 Balance\",\"Ring Level\",\"Ring Balance\",\"N/E Level\",\"N/E Balance\",\"F1 Cutoff\",\"F1 Resonance\",\"F"
    "1 FM\",\"F1 Drive\",\"F1 Pan\",\"F2 Cutoff\",\"F2 Resonance\",\"F2 FM\",\"F2 Drive\",\"F2 Pan\",\"Volume\"]},{\"key\":\""
    "fmod4_amount\",\"name\":\"F4 Amt\",\"short_name\":\"F4AMT\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"smod1_so"
    "urce\",\"name\":\"M1 Src\",\"short_name\":\"M1SRC\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO "
    "2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Keytrack\",\"Velocity\",\"Release Vel\",\""
    "Aftertouch\",\"Poly Pressure\",\"Pitch Bend\",\"Modwheel\",\"Sustain Pedal\",\"Foot Control\",\"Breath Control\","
    "\"Control W\",\"Control X\",\"Control Y\",\"Control Z\",\"Control Delay\",\"Modifier 1\",\"Modifier 2\",\"Modifier "
    "3\",\"Modifier 4\",\"Min\",\"Max\",\"Voice Num\",\"Voice %16\",\"Voice %8\",\"Voice %4\",\"Voice %2\",\"Unison Voice\","
    "\"Uni Detune\",\"Uni De-Pan\",\"Uni De-Oct\"]},{\"key\":\"smod1_destination\",\"name\":\"M1 Dest\",\"short_name\":\"M"
    "1DST\",\"type\":\"enum\",\"options\":[\"Pitch\",\"O1 Pitch\",\"O1 FM\",\"O1 PW\",\"O2 Pitch\",\"O2 FM\",\"O2 PW\",\"O3 Pit"
    "ch\",\"O3 FM\",\"O3 PW\",\"O1 Level\",\"O1 Balance\",\"O2 Level\",\"O2 Balance\",\"O3 Level\",\"O3 Balance\",\"Ring Le"
    "vel\",\"Ring Balance\",\"N/E Level\",\"N/E Balance\",\"F1 Cutoff\",\"F1 Resonance\",\"F1 FM\",\"F1 Drive\",\"F1 Pan\""
    ",\"F2 Cutoff\",\"F2 Resonance\",\"F2 FM\",\"F2 Drive\",\"F2 Pan\",\"Volume\",\"LFO 1 Speed\",\"LFO 2 Speed\",\"LFO 3 "
    "Speed\",\"FE Attack\",\"FE Decay\",\"FE Sustain\",\"FE Release\",\"AE Attack\",\"AE Decay\",\"AE Sustain\",\"AE Rele"
    "ase\",\"Env 3 Attack\",\"Env 3 Decay\",\"Env 3 Sustain\",\"Env 3 Release\",\"Env 4 Attack\",\"Env 4 Decay\",\"Env "
    "4 Sustain\",\"Env 4 Release\",\"M1F Amount\",\"M2F Amount\",\"M1S Amount\",\"M2S Amount\",\"O1 Sub Div\",\"O1 Sub "
    "Volume\",\"O2 Sub Div\",\"O2 Sub Volume\"]},{\"key\":\"smod1_amount\",\"name\":\"M1 Amt\",\"short_name\":\"M1AMT\",\"t"
    "ype\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"smod2_source\",\"name\":\"M2 Src\",\"short_name\":\"M2SRC\",\"type\":\"en"
    "um\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3"
    "\",\"Env 4\",\"Keytrack\",\"Velocity\",\"Release Vel\",\"Aftertouch\",\"Poly Pressure\",\"Pitch Bend\",\"Modwheel\",\""
    "Sustain Pedal\",\"Foot Control\",\"Breath Control\",\"Control W\",\"Control X\",\"Control Y\",\"Control Z\",\"Cont"
    "rol Delay\",\"Modifier 1\",\"Modifier 2\",\"Modifier 3\",\"Modifier 4\",\"Min\",\"Max\",\"Voice Num\",\"Voice %16\",\""
    "Voice %8\",\"Voice %4\",\"Voice %2\",\"Unison Voice\",\"Uni Detune\",\"Uni De-Pan\",\"Uni De-Oct\"]},{\"key\":\"smod"
    "2_destination\",\"name\":\"M2 Dest\",\"short_name\":\"M2DST\",\"type\":\"enum\",\"options\":[\"Pitch\",\"O1 Pitch\",\"O1"
    " FM\",\"O1 PW\",\"O2 Pitch\",\"O2 FM\",\"O2 PW\",\"O3 Pitch\",\"O3 FM\",\"O3 PW\",\"O1 Level\",\"O1 Balance\",\"O2 Level"
    "\",\"O2 Balance\",\"O3 Level\",\"O3 Balance\",\"Ring Level\",\"Ring Balance\",\"N/E Level\",\"N/E Balance\",\"F1 Cut"
    "off\",\"F1 Resonance\",\"F1 FM\",\"F1 Drive\",\"F1 Pan\",\"F2 Cutoff\",\"F2 Resonance\",\"F2 FM\",\"F2 Drive\",\"F2 Pa"
    "n\",\"Volume\",\"LFO 1 Speed\",\"LFO 2 Speed\",\"LFO 3 Speed\",\"FE Attack\",\"FE Decay\",\"FE Sustain\",\"FE Releas"
    "e\",\"AE Attack\",\"AE Decay\",\"AE Sustain\",\"AE Release\",\"Env 3 Attack\",\"Env 3 Decay\",\"Env 3 Sustain\",\"En"
    "v 3 Release\",\"Env 4 Attack\",\"Env 4 Decay\",\"Env 4 Sustain\",\"Env 4 Release\",\"M1F Amount\",\"M2F Amount\","
    "\"M1S Amount\",\"M2S Amount\",\"O1 Sub Div\",\"O1 Sub Volume\",\"O2 Sub Div\",\"O2 Sub Volume\"]},{\"key\":\"smod2_"
    "amount\",\"name\":\"M2 Amt\",\"short_name\":\"M2AMT\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"smod3_source\","
    "\"name\":\"M3 Src\",\"short_name\":\"M3SRC\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LF"
    "O 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Keytrack\",\"Velocity\",\"Release Vel\",\"Aftert"
    "ouch\",\"Poly Pressure\",\"Pitch Bend\",\"Modwheel\",\"Sustain Pedal\",\"Foot Control\",\"Breath Control\",\"Contr"
    "ol W\",\"Control X\",\"Control Y\",\"Control Z\",\"Control Delay\",\"Modifier 1\",\"Modifier 2\",\"Modifier 3\",\"Mo"
    "difier 4\",\"Min\",\"Max\",\"Voice Num\",\"Voice %16\",\"Voice %8\",\"Voice %4\",\"Voice %2\",\"Unison Voice\",\"Uni D"
    "etune\",\"Uni De-Pan\",\"Uni De-Oct\"]},{\"key\":\"smod3_destination\",\"name\":\"M3 Dest\",\"short_name\":\"M3DST\","
    "\"type\":\"enum\",\"options\":[\"Pitch\",\"O1 Pitch\",\"O1 FM\",\"O1 PW\",\"O2 Pitch\",\"O2 FM\",\"O2 PW\",\"O3 Pitch\",\"O"
    "3 FM\",\"O3 PW\",\"O1 Level\",\"O1 Balance\",\"O2 Level\",\"O2 Balance\",\"O3 Level\",\"O3 Balance\",\"Ring Level\",\""
    "Ring Balance\",\"N/E Level\",\"N/E Balance\",\"F1 Cutoff\",\"F1 Resonance\",\"F1 FM\",\"F1 Drive\",\"F1 Pan\",\"F2 C"
    "utoff\",\"F2 Resonance\",\"F2 FM\",\"F2 Drive\",\"F2 Pan\",\"Volume\",\"LFO 1 Speed\",\"LFO 2 Speed\",\"LFO 3 Speed\""
    ",\"FE Attack\",\"FE Decay\",\"FE Sustain\",\"FE Release\",\"AE Attack\",\"AE Decay\",\"AE Sustain\",\"AE Release\",\""
    "Env 3 Attack\",\"Env 3 Decay\",\"Env 3 Sustain\",\"Env 3 Release\",\"Env 4 Attack\",\"Env 4 Decay\",\"Env 4 Sust"
    "ain\",\"Env 4 Release\",\"M1F Amount\",\"M2F Amount\",\"M1S Amount\",\"M2S Amount\",\"O1 Sub Div\",\"O1 Sub Volume"
    "\",\"O2 Sub Div\",\"O2 Sub Volume\"]},{\"key\":\"smod3_amount\",\"name\":\"M3 Amt\",\"short_name\":\"M3AMT\",\"type\":\""
    "int\",\"min\":-64,\"max\":63},{\"key\":\"smod4_source\",\"name\":\"M4 Src\",\"short_name\":\"M4SRC\",\"type\":\"enum\",\"o"
    "ptions\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env"
    " 4\",\"Keytrack\",\"Velocity\",\"Release Vel\",\"Aftertouch\",\"Poly Pressure\",\"Pitch Bend\",\"Modwheel\",\"Sustai"
    "n Pedal\",\"Foot Control\",\"Breath Control\",\"Control W\",\"Control X\",\"Control Y\",\"Control Z\",\"Control De"
    "lay\",\"Modifier 1\",\"Modifier 2\",\"Modifier 3\",\"Modifier 4\",\"Min\",\"Max\",\"Voice Num\",\"Voice %16\",\"Voice "
    "%8\",\"Voice %4\",\"Voice %2\",\"Unison Voice\",\"Uni Detune\",\"Uni De-Pan\",\"Uni De-Oct\"]},{\"key\":\"smod4_dest"
    "ination\",\"name\":\"M4 Dest\",\"short_name\":\"M4DST\",\"type\":\"enum\",\"options\":[\"Pitch\",\"O1 Pitch\",\"O1 FM\",\""
    "O1 PW\",\"O2 Pitch\",\"O2 FM\",\"O2 PW\",\"O3 Pitch\",\"O3 FM\",\"O3 PW\",\"O1 Level\",\"O1 Balance\",\"O2 Level\",\"O2 "
    "Balance\",\"O3 Level\",\"O3 Balance\",\"Ring Level\",\"Ring Balance\",\"N/E Level\",\"N/E Balance\",\"F1 Cutoff\",\""
    "F1 Resonance\",\"F1 FM\",\"F1 Drive\",\"F1 Pan\",\"F2 Cutoff\",\"F2 Resonance\",\"F2 FM\",\"F2 Drive\",\"F2 Pan\",\"Vo"
    "lume\",\"LFO 1 Speed\",\"LFO 2 Speed\",\"LFO 3 Speed\",\"FE Attack\",\"FE Decay\",\"FE Sustain\",\"FE Release\",\"AE"
    " Attack\",\"AE Decay\",\"AE Sustain\",\"AE Release\",\"Env 3 Attack\",\"Env 3 Decay\",\"Env 3 Sustain\",\"Env 3 Re"
    "lease\",\"Env 4 Attack\",\"Env 4 Decay\",\"Env 4 Sustain\",\"Env 4 Release\",\"M1F Amount\",\"M2F Amount\",\"M1S A"
    "mount\",\"M2S Amount\",\"O1 Sub Div\",\"O1 Sub Volume\",\"O2 Sub Div\",\"O2 Sub Volume\"]},{\"key\":\"smod4_amount"
    "\",\"name\":\"M4 Amt\",\"short_name\":\"M4AMT\",\"type\":\"int\",\"min\":-64,\"max\":63},{\"key\":\"modif1_source1\",\"nam"
    "e\":\"M1 Src1\",\"short_name\":\"M1S1\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 "
    "* AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Keytrack\",\"Velocity\",\"Release Vel\",\"Aftertouch"
    "\",\"Poly Pressure\",\"Pitch Bend\",\"Modwheel\",\"Sustain Pedal\",\"Foot Control\",\"Breath Control\",\"Control W"
    "\",\"Control X\",\"Control Y\",\"Control Z\",\"Control Delay\",\"Modifier 1\",\"Modifier 2\",\"Modifier 3\",\"Modifi"
    "er 4\",\"Min\",\"Max\",\"Voice Num\",\"Voice %16\",\"Voice %8\",\"Voice %4\",\"Voice %2\",\"Unison Voice\",\"Uni Detun"
    "e\",\"Uni De-Pan\",\"Uni De-Oct\"]},{\"key\":\"modif1_source2\",\"name\":\"M1 Src2\",\"short_name\":\"M1S2\",\"type\":\""
    "enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env"
    " 3\",\"Env 4\",\"Keytrack\",\"Velocity\",\"Release Vel\",\"Aftertouch\",\"Poly Pressure\",\"Pitch Bend\",\"Modwheel\""
    ",\"Sustain Pedal\",\"Foot Control\",\"Breath Control\",\"Control W\",\"Control X\",\"Control Y\",\"Control Z\",\"Co"
    "ntrol Delay\",\"Modifier 1\",\"Modifier 2\",\"Modifier 3\",\"Modifier 4\",\"Min\",\"Max\",\"Voice Num\",\"Voice %16\""
    ",\"Voice %8\",\"Voice %4\",\"Voice %2\",\"Unison Voice\",\"Uni Detune\",\"Uni De-Pan\",\"Uni De-Oct\"]},{\"key\":\"mo"
    "dif1_operator\",\"name\":\"M1 Op\",\"short_name\":\"M1OP\",\"type\":\"enum\",\"options\":[\"+\",\"-\",\"*\",\"AND\",\"OR\",\"X"
    "OR\",\"Max\",\"Min\"]},{\"key\":\"modif1_constant\",\"name\":\"M1 Const\",\"short_name\":\"M1CN\",\"type\":\"int\",\"min\":"
    "0,\"max\":127},{\"key\":\"modif2_source1\",\"name\":\"M2 Src1\",\"short_name\":\"M2S1\",\"type\":\"enum\",\"options\":[\""
    "Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Keytr"
    "ack\",\"Velocity\",\"Release Vel\",\"Aftertouch\",\"Poly Pressure\",\"Pitch Bend\",\"Modwheel\",\"Sustain Pedal\",\""
    "Foot Control\",\"Breath Control\",\"Control W\",\"Control X\",\"Control Y\",\"Control Z\",\"Control Delay\",\"Modi"
    "fier 1\",\"Modifier 2\",\"Modifier 3\",\"Modifier 4\",\"Min\",\"Max\",\"Voice Num\",\"Voice %16\",\"Voice %8\",\"Voice"
    " %4\",\"Voice %2\",\"Unison Voice\",\"Uni Detune\",\"Uni De-Pan\",\"Uni De-Oct\"]},{\"key\":\"modif2_source2\",\"nam"
    "e\":\"M2 Src2\",\"short_name\":\"M2S2\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 "
    "* AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Keytrack\",\"Velocity\",\"Release Vel\",\"Aftertouch"
    "\",\"Poly Pressure\",\"Pitch Bend\",\"Modwheel\",\"Sustain Pedal\",\"Foot Control\",\"Breath Control\",\"Control W"
    "\",\"Control X\",\"Control Y\",\"Control Z\",\"Control Delay\",\"Modifier 1\",\"Modifier 2\",\"Modifier 3\",\"Modifi"
    "er 4\",\"Min\",\"Max\",\"Voice Num\",\"Voice %16\",\"Voice %8\",\"Voice %4\",\"Voice %2\",\"Unison Voice\",\"Uni Detun"
    "e\",\"Uni De-Pan\",\"Uni De-Oct\"]},{\"key\":\"modif2_operator\",\"name\":\"M2 Op\",\"short_name\":\"M2OP\",\"type\":\"e"
    "num\",\"options\":[\"+\",\"-\",\"*\",\"AND\",\"OR\",\"XOR\",\"Max\",\"Min\"]},{\"key\":\"modif2_constant\",\"name\":\"M2 Const"
    "\",\"short_name\":\"M2CN\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"modif3_source1\",\"name\":\"M3 Src1\",\"shor"
    "t_name\":\"M3S1\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Fil"
    "ter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Keytrack\",\"Velocity\",\"Release Vel\",\"Aftertouch\",\"Poly Pressure\","
    "\"Pitch Bend\",\"Modwheel\",\"Sustain Pedal\",\"Foot Control\",\"Breath Control\",\"Control W\",\"Control X\",\"Con"
    "trol Y\",\"Control Z\",\"Control Delay\",\"Modifier 1\",\"Modifier 2\",\"Modifier 3\",\"Modifier 4\",\"Min\",\"Max\","
    "\"Voice Num\",\"Voice %16\",\"Voice %8\",\"Voice %4\",\"Voice %2\",\"Unison Voice\",\"Uni Detune\",\"Uni De-Pan\",\"U"
    "ni De-Oct\"]},{\"key\":\"modif3_source2\",\"name\":\"M3 Src2\",\"short_name\":\"M3S2\",\"type\":\"enum\",\"options\":[\""
    "Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Keytr"
    "ack\",\"Velocity\",\"Release Vel\",\"Aftertouch\",\"Poly Pressure\",\"Pitch Bend\",\"Modwheel\",\"Sustain Pedal\",\""
    "Foot Control\",\"Breath Control\",\"Control W\",\"Control X\",\"Control Y\",\"Control Z\",\"Control Delay\",\"Modi"
    "fier 1\",\"Modifier 2\",\"Modifier 3\",\"Modifier 4\",\"Min\",\"Max\",\"Voice Num\",\"Voice %16\",\"Voice %8\",\"Voice"
    " %4\",\"Voice %2\",\"Unison Voice\",\"Uni Detune\",\"Uni De-Pan\",\"Uni De-Oct\"]},{\"key\":\"modif3_operator\",\"na"
    "me\":\"M3 Op\",\"short_name\":\"M3OP\",\"type\":\"enum\",\"options\":[\"+\",\"-\",\"*\",\"AND\",\"OR\",\"XOR\",\"Max\",\"Min\"]},"
    "{\"key\":\"modif3_constant\",\"name\":\"M3 Const\",\"short_name\":\"M3CN\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key"
    "\":\"modif4_source1\",\"name\":\"M4 Src1\",\"short_name\":\"M4S1\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO "
    "1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Keytrack\",\"Velocity\",\"R"
    "elease Vel\",\"Aftertouch\",\"Poly Pressure\",\"Pitch Bend\",\"Modwheel\",\"Sustain Pedal\",\"Foot Control\",\"Bre"
    "ath Control\",\"Control W\",\"Control X\",\"Control Y\",\"Control Z\",\"Control Delay\",\"Modifier 1\",\"Modifier "
    "2\",\"Modifier 3\",\"Modifier 4\",\"Min\",\"Max\",\"Voice Num\",\"Voice %16\",\"Voice %8\",\"Voice %4\",\"Voice %2\",\"U"
    "nison Voice\",\"Uni Detune\",\"Uni De-Pan\",\"Uni De-Oct\"]},{\"key\":\"modif4_source2\",\"name\":\"M4 Src2\",\"shor"
    "t_name\":\"M4S2\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO 2 * AT\",\"LFO 3\",\"Fil"
    "ter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Keytrack\",\"Velocity\",\"Release Vel\",\"Aftertouch\",\"Poly Pressure\","
    "\"Pitch Bend\",\"Modwheel\",\"Sustain Pedal\",\"Foot Control\",\"Breath Control\",\"Control W\",\"Control X\",\"Con"
    "trol Y\",\"Control Z\",\"Control Delay\",\"Modifier 1\",\"Modifier 2\",\"Modifier 3\",\"Modifier 4\",\"Min\",\"Max\","
    "\"Voice Num\",\"Voice %16\",\"Voice %8\",\"Voice %4\",\"Voice %2\",\"Unison Voice\",\"Uni Detune\",\"Uni De-Pan\",\"U"
    "ni De-Oct\"]},{\"key\":\"modif4_operator\",\"name\":\"M4 Op\",\"short_name\":\"M4OP\",\"type\":\"enum\",\"options\":[\"+"
    "\",\"-\",\"*\",\"AND\",\"OR\",\"XOR\",\"Max\",\"Min\"]},{\"key\":\"modif4_constant\",\"name\":\"M4 Const\",\"short_name\":\"M4"
    "CN\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"arp_mode\",\"name\":\"Mode\",\"short_name\":\"MODE\",\"type\":\"enum"
    "\",\"options\":[\"Off\",\"On\",\"One Shot\",\"Hold\"]},{\"key\":\"arp_pattern\",\"name\":\"Pattern\",\"type\":\"enum\",\"opt"
    "ions\":[\"Off\",\"User\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\"]},{\"key\":\"arp_"
    "clock\",\"name\":\"Clock\",\"type\":\"enum\",\"options\":[\"1/64\",\"1/32 T\",\"5/192\",\"1/32\",\"7/192\",\"1/16 T\",\"1/64"
    " D\",\"10/192\",\"11/192\",\"1/16\",\"13/192\",\"14/192\",\"15/192\",\"1/8 T\",\"17/192\",\"1/16 D\",\"19/192\",\"20/192\","
    "\"21/192\",\"22/192\",\"23/192\",\"1/8\",\"25/192\",\"26/192\",\"27/192\",\"28/192\",\"29/192\",\"30/192\",\"31/192\",\"1/4"
    " T\",\"33/192\",\"34/192\",\"35/192\",\"1/8 D\",\"37/192\",\"38/192\",\"39/192\",\"40/192\",\"41/192\",\"42/192\",\"43/192"
    "\",\"44/192\",\"45/192\",\"46/192\",\"47/192\",\"1/4\",\"49/192\",\"50/192\",\"51/192\",\"52/192\",\"53/192\",\"54/192\",\"5"
    "5/192\",\"56/192\",\"57/192\",\"58/192\",\"59/192\",\"60/192\",\"61/192\",\"62/192\",\"63/192\",\"1/2 T\",\"65/192\",\"66/"
    "192\",\"67/192\",\"68/192\",\"69/192\",\"70/192\",\"71/192\",\"1/4 D\",\"73/192\",\"74/192\",\"75/192\",\"76/192\",\"77/19"
    "2\",\"78/192\",\"79/192\",\"80/192\",\"81/192\",\"82/192\",\"83/192\",\"84/192\",\"85/192\",\"86/192\",\"87/192\",\"88/192"
    "\",\"89/192\",\"90/192\",\"91/192\",\"92/192\",\"93/192\",\"94/192\",\"95/192\",\"1/2\",\"97/192\",\"98/192\",\"99/192\",\"1"
    "00/192\",\"101/192\",\"102/192\",\"103/192\",\"104/192\",\"105/192\",\"106/192\",\"107/192\",\"108/192\",\"109/192\",\"1"
    "10/192\",\"111/192\",\"112/192\",\"113/192\",\"114/192\",\"115/192\",\"116/192\",\"117/192\",\"118/192\",\"119/192\",\"1"
    "20/192\",\"121/192\",\"122/192\",\"123/192\",\"124/192\",\"125/192\",\"126/192\",\"127/192\",\"1/1 T\",\"129/192\",\"130"
    "/192\"]},{\"key\":\"arp_length\",\"name\":\"Length\",\"type\":\"enum\",\"options\":[\"1/128 T\",\"1/64 T\",\"1/64\",\"1/32"
    " T\",\"5/192\",\"1/32\",\"7/192\",\"1/16 T\",\"1/64 D\",\"10/192\",\"11/192\",\"1/16\",\"13/192\",\"14/192\",\"15/192\",\"1/"
    "8 T\",\"17/192\",\"1/16 D\",\"19/192\",\"20/192\",\"21/192\",\"22/192\",\"23/192\",\"1/8\",\"25/192\",\"26/192\",\"27/192\""
    ",\"28/192\",\"29/192\",\"30/192\",\"31/192\",\"1/4 T\",\"33/192\",\"34/192\",\"35/192\",\"1/8 D\",\"37/192\",\"38/192\",\"3"
    "9/192\",\"40/192\",\"41/192\",\"42/192\",\"43/192\",\"44/192\",\"45/192\",\"46/192\",\"47/192\",\"1/4\",\"49/192\",\"50/19"
    "2\",\"51/192\",\"52/192\",\"53/192\",\"54/192\",\"55/192\",\"56/192\",\"57/192\",\"58/192\",\"59/192\",\"60/192\",\"61/192"
    "\",\"62/192\",\"63/192\",\"1/2 T\",\"65/192\",\"66/192\",\"67/192\",\"68/192\",\"69/192\",\"70/192\",\"71/192\",\"1/4 D\",\""
    "73/192\",\"74/192\",\"75/192\",\"76/192\",\"77/192\",\"78/192\",\"79/192\",\"80/192\",\"81/192\",\"82/192\",\"83/192\",\"8"
    "4/192\",\"85/192\",\"86/192\",\"87/192\",\"88/192\",\"89/192\",\"90/192\",\"91/192\",\"92/192\",\"93/192\",\"94/192\",\"95"
    "/192\",\"1/2\",\"97/192\",\"98/192\",\"99/192\",\"100/192\",\"101/192\",\"102/192\",\"103/192\",\"104/192\",\"105/192\",\""
    "106/192\",\"107/192\",\"108/192\",\"109/192\",\"110/192\",\"111/192\",\"112/192\",\"113/192\",\"114/192\",\"115/192\",\""
    "116/192\",\"117/192\",\"118/192\",\"119/192\",\"120/192\",\"121/192\",\"122/192\",\"123/192\",\"124/192\",\"125/192\",\""
    "126/192\",\"127/192\",\"Legato\"],\"default\":11},{\"key\":\"arp_octave_range\",\"name\":\"Octaves\",\"type\":\"enum\","
    "\"options\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"]},{\"key\":\"arp_direction\",\"name\":\"Direction\",\"typ"
    "e\":\"enum\",\"options\":[\"Up\",\"Down\",\"Alt Up\",\"Alt Down\"]},{\"key\":\"arp_sort_order\",\"name\":\"Sort Order\",\""
    "type\":\"enum\",\"options\":[\"As Played\",\"Reversed\",\"Note Low-High\",\"Note High-Low\",\"Vel Low-High\",\"Vel H"
    "igh-Low\"]},{\"key\":\"arp_velo_mode\",\"name\":\"Velocity\",\"type\":\"enum\",\"options\":[\"Each Note\",\"First Note"
    "\",\"Last Note\"]},{\"key\":\"arp_max_notes\",\"name\":\"Max Notes\",\"type\":\"int\",\"min\":0,\"max\":15,\"default\":15"
    "},{\"key\":\"arp_t_factor\",\"name\":\"Timing\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":127},{\"key\":\"arp_sa"
    "me_note_overlap\",\"name\":\"Overlap\",\"type\":\"int\",\"min\":0,\"max\":1},{\"key\":\"arp_pattern_reset\",\"name\":\"P"
    "at Reset\",\"type\":\"int\",\"min\":0,\"max\":1},{\"key\":\"arp_pattern_length\",\"name\":\"Pat Length\",\"type\":\"enum"
    "\",\"options\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\"]},{\"key\":\"tempo\""
    ",\"name\":\"Tempo\",\"type\":\"enum\",\"options\":[\"40\",\"42\",\"44\",\"46\",\"48\",\"50\",\"52\",\"54\",\"56\",\"58\",\"60\",\"62\""
    ",\"64\",\"66\",\"68\",\"70\",\"72\",\"74\",\"76\",\"78\",\"80\",\"82\",\"84\",\"86\",\"88\",\"90\",\"91\",\"92\",\"93\",\"94\",\"95\",\"96\""
    ",\"97\",\"98\",\"99\",\"100\",\"101\",\"102\",\"103\",\"104\",\"105\",\"106\",\"107\",\"108\",\"109\",\"110\",\"111\",\"112\",\"113\","
    "\"114\",\"115\",\"116\",\"117\",\"118\",\"119\",\"120\",\"121\",\"122\",\"123\",\"124\",\"125\",\"126\",\"127\",\"128\",\"129\",\"130"
    "\",\"131\",\"132\",\"133\",\"134\",\"135\",\"136\",\"137\",\"138\",\"139\",\"140\",\"141\",\"142\",\"143\",\"144\",\"145\",\"146\",\"1"
    "47\",\"148\",\"149\",\"150\",\"151\",\"152\",\"153\",\"154\",\"155\",\"156\",\"157\",\"158\",\"159\",\"160\",\"161\",\"162\",\"163\","
    "\"164\",\"165\",\"170\",\"175\",\"180\",\"185\",\"190\",\"195\",\"200\",\"205\",\"210\",\"215\",\"220\",\"225\",\"230\",\"235\",\"240"
    "\",\"245\",\"250\",\"255\",\"260\",\"265\",\"270\",\"275\",\"280\",\"285\",\"290\",\"295\",\"300\"],\"default\":55},{\"key\":\"voi"
    "ce_mode\",\"name\":\"Voice Mode\",\"short_name\":\"VOICE\",\"type\":\"int\",\"min\":0,\"max\":1},{\"key\":\"unison_count"
    "\",\"name\":\"Count\",\"type\":\"enum\",\"options\":[\"Off\",\"Dual\",\"3\",\"4\",\"5\",\"6\"]},{\"key\":\"unison_detune\",\"nam"
    "e\":\"Detune\",\"short_name\":\"DTUNE\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"sync\",\"name\":\"Sync\",\"short_"
    "name\":\"SYNC\",\"type\":\"int\",\"min\":0,\"max\":1},{\"key\":\"glide_mode\",\"name\":\"Glide Mode\",\"short_name\":\"GLI"
    "DE\",\"type\":\"int\",\"min\":0,\"max\":4},{\"key\":\"glide_rate\",\"name\":\"Rate\",\"type\":\"int\",\"min\":0,\"max\":127},"
    "{\"key\":\"pitchmod_src\",\"name\":\"Src\",\"type\":\"enum\",\"options\":[\"Off\",\"LFO 1\",\"LFO 1 * MW\",\"LFO 2\",\"LFO "
    "2 * AT\",\"LFO 3\",\"Filter Env\",\"Amp Env\",\"Env 3\",\"Env 4\",\"Velocity\",\"Modwheel\",\"Pitch Bend\",\"Aftertouc"
    "h\"]},{\"key\":\"pitchmod_amount\",\"name\":\"Amount\",\"short_name\":\"AMT\",\"type\":\"int\",\"min\":-64,\"max\":63},{\""
    "key\":\"fx1_type\",\"name\":\"FX1 Type\",\"short_name\":\"TYPE\",\"type\":\"enum\",\"options\":[\"Bypass\",\"Chorus\",\"Fl"
    "anger\",\"Phaser\",\"Overdrive\",\"Five FX\",\"Vocoder\"]},{\"key\":\"fx1_mix\",\"name\":\"FX1 Mix\",\"short_name\":\"MI"
    "X\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"fx1_chorus_delay\",\"name\":\"Chorus Delay\",\"type\":\"int\",\"min"
    "\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":1}},{\"key\":\"fx1_chorus_depth\",\"name\":\"Chorus D"
    "epth\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":1}},{\"key\":\"fx1_chorus_"
    "speed\",\"name\":\"Chorus Speed\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":"
    "1}},{\"key\":\"fx1_flanger_depth\",\"name\":\"Flanger Depth\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\""
    "key\":\"fx1_type\",\"equals\":2}},{\"key\":\"fx1_flanger_feedback\",\"name\":\"Flanger Feedback\",\"type\":\"int\",\"m"
    "in\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":2}},{\"key\":\"fx1_flanger_polarity\",\"name\":\"Fl"
    "anger Polarity\",\"type\":\"int\",\"min\":0,\"max\":1,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":2}},{\"key\":\"fx1"
    "_flanger_speed\",\"name\":\"Flanger Speed\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\""
    ",\"equals\":2}},{\"key\":\"fx1_phaser_center\",\"name\":\"Phaser Center\",\"type\":\"int\",\"min\":0,\"max\":127,\"visi"
    "ble_if\":{\"key\":\"fx1_type\",\"equals\":3}},{\"key\":\"fx1_phaser_depth\",\"name\":\"Phaser Depth\",\"type\":\"int\","
    "\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":3}},{\"key\":\"fx1_phaser_feedback\",\"name\":\"P"
    "haser Feedback\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":3}},{\"key\":\"f"
    "x1_phaser_polarity\",\"name\":\"Phaser Polarity\",\"type\":\"int\",\"min\":0,\"max\":1,\"visible_if\":{\"key\":\"fx1_t"
    "ype\",\"equals\":3}},{\"key\":\"fx1_phaser_spacing\",\"name\":\"Phaser Spacing\",\"type\":\"int\",\"min\":0,\"max\":127"
    ",\"visible_if\":{\"key\":\"fx1_type\",\"equals\":3}},{\"key\":\"fx1_phaser_speed\",\"name\":\"Phaser Speed\",\"type\":"
    "\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":3}},{\"key\":\"fx1_overdrive_cutoff\",\"n"
    "ame\":\"Overdrive Cutoff\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":4}},{"
    "\"key\":\"fx1_overdrive_drive\",\"name\":\"Overdrive Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"k"
    "ey\":\"fx1_type\",\"equals\":4}},{\"key\":\"fx1_overdrive_post_gain\",\"name\":\"Overdrive Post Gain\",\"type\":\"in"
    "t\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":4}},{\"key\":\"fx1_vocoder_analysis_freq_h"
    "igh\",\"name\":\"Vocoder Analysis Freq High\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_typ"
    "e\",\"equals\":6}},{\"key\":\"fx1_vocoder_analysis_freq_low\",\"name\":\"Vocoder Analysis Freq Low\",\"type\":\"in"
    "t\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":6}},{\"key\":\"fx1_vocoder_analysis_signal"
    "\",\"name\":\"Vocoder Analysis Signal\",\"type\":\"int\",\"min\":0,\"max\":8,\"visible_if\":{\"key\":\"fx1_type\",\"equa"
    "ls\":6}},{\"key\":\"fx1_vocoder_attack\",\"name\":\"Vocoder Attack\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_"
    "if\":{\"key\":\"fx1_type\",\"equals\":6}},{\"key\":\"fx1_vocoder_bands\",\"name\":\"Vocoder Bands\",\"type\":\"int\",\"m"
    "in\":2,\"max\":25,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":6}},{\"key\":\"fx1_vocoder_bandwidth\",\"name\":\"Vo"
    "coder Bandwidth\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":6}},{\"key\":\""
    "fx1_vocoder_decay\",\"name\":\"Vocoder Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_ty"
    "pe\",\"equals\":6}},{\"key\":\"fx1_vocoder_eq_band_mid\",\"name\":\"Vocoder EQ Band Mid\",\"type\":\"int\",\"min\":0,"
    "\"max\":24,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":6}},{\"key\":\"fx1_vocoder_eq_level_high\",\"name\":\"Voco"
    "der EQ Level High\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":6}},{\"key\""
    ":\"fx1_vocoder_eq_level_low\",\"name\":\"Vocoder EQ Level Low\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if"
    "\":{\"key\":\"fx1_type\",\"equals\":6}},{\"key\":\"fx1_vocoder_eq_level_mid\",\"name\":\"Vocoder EQ Level Mid\",\"ty"
    "pe\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":6}},{\"key\":\"fx1_vocoder_offset_h"
    "i\",\"name\":\"Vocoder Offset Hi\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\""
    ":6}},{\"key\":\"fx1_vocoder_offset_s\",\"name\":\"Vocoder Offset S\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible"
    "_if\":{\"key\":\"fx1_type\",\"equals\":6}},{\"key\":\"fx1_vocoder_resonance\",\"name\":\"Vocoder Resonance\",\"type\""
    ":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx1_type\",\"equals\":6}},{\"key\":\"fx2_type\",\"name\":\"FX2 T"
    "ype\",\"short_name\":\"TYPE\",\"type\":\"enum\",\"options\":[\"Bypass\",\"Chorus\",\"Flanger\",\"Phaser\",\"Overdrive\",\""
    "Five FX\",\"Vocoder\",\"Delay\",\"Reverb\",\"5.1 Delay\",\"5.1 Delay Clocked\"]},{\"key\":\"fx2_mix\",\"name\":\"FX2 M"
    "ix\",\"short_name\":\"MIX\",\"type\":\"int\",\"min\":0,\"max\":127},{\"key\":\"fx2_chorus_delay\",\"name\":\"Chorus Dela"
    "y\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":1}},{\"key\":\"fx2_chorus_dep"
    "th\",\"name\":\"Chorus Depth\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":1}}"
    ",{\"key\":\"fx2_chorus_speed\",\"name\":\"Chorus Speed\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":"
    "\"fx2_type\",\"equals\":1}},{\"key\":\"fx2_flanger_depth\",\"name\":\"Flanger Depth\",\"type\":\"int\",\"min\":0,\"max\""
    ":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":2}},{\"key\":\"fx2_flanger_feedback\",\"name\":\"Flanger Feedb"
    "ack\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":2}},{\"key\":\"fx2_flanger_"
    "polarity\",\"name\":\"Flanger Polarity\",\"type\":\"int\",\"min\":0,\"max\":1,\"visible_if\":{\"key\":\"fx2_type\",\"equ"
    "als\":2}},{\"key\":\"fx2_flanger_speed\",\"name\":\"Flanger Speed\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_i"
    "f\":{\"key\":\"fx2_type\",\"equals\":2}},{\"key\":\"fx2_phaser_center\",\"name\":\"Phaser Center\",\"type\":\"int\",\"mi"
    "n\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":3}},{\"key\":\"fx2_phaser_depth\",\"name\":\"Phaser "
    "Depth\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":3}},{\"key\":\"fx2_phaser"
    "_feedback\",\"name\":\"Phaser Feedback\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"e"
    "quals\":3}},{\"key\":\"fx2_phaser_polarity\",\"name\":\"Phaser Polarity\",\"type\":\"int\",\"min\":0,\"max\":1,\"visib"
    "le_if\":{\"key\":\"fx2_type\",\"equals\":3}},{\"key\":\"fx2_phaser_spacing\",\"name\":\"Phaser Spacing\",\"type\":\"in"
    "t\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":3}},{\"key\":\"fx2_phaser_speed\",\"name\":\"P"
    "haser Speed\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":3}},{\"key\":\"fx2_"
    "overdrive_cutoff\",\"name\":\"Overdrive Cutoff\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_"
    "type\",\"equals\":4}},{\"key\":\"fx2_overdrive_drive\",\"name\":\"Overdrive Drive\",\"type\":\"int\",\"min\":0,\"max\":"
    "127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":4}},{\"key\":\"fx2_overdrive_post_gain\",\"name\":\"Overdrive P"
    "ost Gain\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":4}},{\"key\":\"fx2_del"
    "ay_autopan\",\"name\":\"Delay Autopan\",\"type\":\"int\",\"min\":0,\"max\":1,\"visible_if\":{\"key\":\"fx2_type\",\"equa"
    "ls\":7}},{\"key\":\"fx2_delay_cutoff\",\"name\":\"Delay Cutoff\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":"
    "{\"key\":\"fx2_type\",\"equals\":7}},{\"key\":\"fx2_delay_feedback\",\"name\":\"Delay Feedback\",\"type\":\"int\",\"min"
    "\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":7}},{\"key\":\"fx2_delay_polarity\",\"name\":\"Delay "
    "Polarity\",\"type\":\"int\",\"min\":0,\"max\":1,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":7}},{\"key\":\"fx2_rever"
    "b_damping\",\"name\":\"Reverb Damping\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"eq"
    "uals\":8}},{\"key\":\"fx2_reverb_decay\",\"name\":\"Reverb Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if"
    "\":{\"key\":\"fx2_type\",\"equals\":8}},{\"key\":\"fx2_reverb_diffusion\",\"name\":\"Reverb Diffusion\",\"type\":\"int"
    "\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":8}},{\"key\":\"fx2_reverb_highpass\",\"name\":"
    "\"Reverb Highpass\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":8}},{\"key\":"
    "\"fx2_reverb_lowpass\",\"name\":\"Reverb Lowpass\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2"
    "_type\",\"equals\":8}},{\"key\":\"fx2_reverb_pre_delay\",\"name\":\"Reverb Pre Delay\",\"type\":\"int\",\"min\":0,\"ma"
    "x\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":8}},{\"key\":\"fx2_reverb_shape\",\"name\":\"Reverb Shape\",\""
    "type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":8}},{\"key\":\"fx2_reverb_size\",\""
    "name\":\"Reverb Size\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":8}},{\"key"
    "\":\"fx2_vocoder_analysis_freq_high\",\"name\":\"Vocoder Analysis Freq High\",\"type\":\"int\",\"min\":0,\"max\":12"
    "7,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":6}},{\"key\":\"fx2_vocoder_analysis_freq_low\",\"name\":\"Vocoder"
    " Analysis Freq Low\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":6}},{\"key"
    "\":\"fx2_vocoder_analysis_signal\",\"name\":\"Vocoder Analysis Signal\",\"type\":\"int\",\"min\":0,\"max\":8,\"visib"
    "le_if\":{\"key\":\"fx2_type\",\"equals\":6}},{\"key\":\"fx2_vocoder_attack\",\"name\":\"Vocoder Attack\",\"type\":\"in"
    "t\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":6}},{\"key\":\"fx2_vocoder_bands\",\"name\":\""
    "Vocoder Bands\",\"type\":\"int\",\"min\":2,\"max\":25,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":6}},{\"key\":\"fx2"
    "_vocoder_bandwidth\",\"name\":\"Vocoder Bandwidth\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"f"
    "x2_type\",\"equals\":6}},{\"key\":\"fx2_vocoder_decay\",\"name\":\"Vocoder Decay\",\"type\":\"int\",\"min\":0,\"max\":1"
    "27,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":6}},{\"key\":\"fx2_vocoder_eq_band_mid\",\"name\":\"Vocoder EQ B"
    "and Mid\",\"type\":\"int\",\"min\":0,\"max\":24,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":6}},{\"key\":\"fx2_vocod"
    "er_eq_level_high\",\"name\":\"Vocoder EQ Level High\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":"
    "\"fx2_type\",\"equals\":6}},{\"key\":\"fx2_vocoder_eq_level_low\",\"name\":\"Vocoder EQ Level Low\",\"type\":\"int\""
    ",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":6}},{\"key\":\"fx2_vocoder_eq_level_mid\",\"na"
    "me\":\"Vocoder EQ Level Mid\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":6}"
    "},{\"key\":\"fx2_vocoder_offset_hi\",\"name\":\"Vocoder Offset Hi\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_"
    "if\":{\"key\":\"fx2_type\",\"equals\":6}},{\"key\":\"fx2_vocoder_offset_s\",\"name\":\"Vocoder Offset S\",\"type\":\"i"
    "nt\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":6}},{\"key\":\"fx2_vocoder_resonance\",\"na"
    "me\":\"Vocoder Resonance\",\"type\":\"int\",\"min\":0,\"max\":127,\"visible_if\":{\"key\":\"fx2_type\",\"equals\":6}}";

static const char g_uiHierarchy[] =
    "{\"pad_layout\":\"chromatic\",\"levels\":{\"osc1\":{\"label\":\"Osc 1\",\"children\":null,\"knobs\":[\"osc1_shape\",\"o"
    "sc1_octave\",\"osc1_semi\",\"osc1_detune\",\"osc1_pulse_width\",\"osc1_pwm\",\"osc1_pwm_source\",\"osc1_key_trac"
    "k\"],\"params\":[{\"key\":\"osc1_shape\",\"label\":\"Shape\",\"short_name\":\"SHAPE\"},{\"key\":\"osc1_octave\",\"label\""
    ":\"Octave\",\"short_name\":\"OCT\"},{\"key\":\"osc1_semi\",\"label\":\"Semi\",\"short_name\":\"SEMI\"},{\"key\":\"osc1_de"
    "tune\",\"label\":\"Detune\",\"short_name\":\"DTUNE\"},{\"key\":\"osc1_pulse_width\",\"label\":\"Pulse Width\",\"short_"
    "name\":\"PW\"},{\"key\":\"osc1_pwm\",\"label\":\"PWM\",\"short_name\":\"PWM\"},{\"key\":\"osc1_pwm_source\",\"label\":\"PW"
    "M Source\",\"short_name\":\"PWSRC\"},{\"key\":\"osc1_key_track\",\"label\":\"Keytrack\"},{\"key\":\"osc1_bend_range\""
    ",\"label\":\"Bend\"},{\"key\":\"osc1_fm_source\",\"label\":\"FM Source\",\"short_name\":\"FMSRC\"},{\"key\":\"osc1_fm_a"
    "mount\",\"label\":\"FM Amt\"},{\"key\":\"osc1_sub_freq_div\",\"label\":\"Sub Div\"},{\"key\":\"osc1_sub_volume\",\"lab"
    "el\":\"Sub Volume\",\"short_name\":\"SUBVL\"}]},\"osc2\":{\"label\":\"Osc 2\",\"children\":null,\"knobs\":[\"osc2_shap"
    "e\",\"osc2_octave\",\"osc2_semi\",\"osc2_detune\",\"osc2_pulse_width\",\"osc2_pwm\",\"osc2_pwm_source\",\"osc2_key"
    "_track\"],\"params\":[{\"key\":\"osc2_shape\",\"label\":\"Shape\",\"short_name\":\"SHAPE\"},{\"key\":\"osc2_octave\",\"l"
    "abel\":\"Octave\",\"short_name\":\"OCT\"},{\"key\":\"osc2_semi\",\"label\":\"Semi\",\"short_name\":\"SEMI\"},{\"key\":\"os"
    "c2_detune\",\"label\":\"Detune\",\"short_name\":\"DTUNE\"},{\"key\":\"osc2_pulse_width\",\"label\":\"Pulse Width\",\"s"
    "hort_name\":\"PW\"},{\"key\":\"osc2_pwm\",\"label\":\"PWM\",\"short_name\":\"PWM\"},{\"key\":\"osc2_pwm_source\",\"label"
    "\":\"PWM Source\",\"short_name\":\"PWSRC\"},{\"key\":\"osc2_key_track\",\"label\":\"Keytrack\"},{\"key\":\"osc2_bend_r"
    "ange\",\"label\":\"Bend\"},{\"key\":\"osc2_fm_source\",\"label\":\"FM Source\",\"short_name\":\"FMSRC\"},{\"key\":\"osc2"
    "_fm_amount\",\"label\":\"FM Amt\"},{\"key\":\"osc2_sub_freq_div\",\"label\":\"Sub Div\"},{\"key\":\"osc2_sub_volume\""
    ",\"label\":\"Sub Volume\",\"short_name\":\"SUBVL\"}]},\"osc3\":{\"label\":\"Osc 3\",\"children\":null,\"knobs\":[\"osc3"
    "_shape\",\"osc3_octave\",\"osc3_semi\",\"osc3_detune\",\"osc3_pulse_width\",\"osc3_pwm\",\"osc3_pwm_source\",\"osc"
    "3_key_track\"],\"params\":[{\"key\":\"osc3_shape\",\"label\":\"Shape\",\"short_name\":\"SHAPE\"},{\"key\":\"osc3_octav"
    "e\",\"label\":\"Octave\",\"short_name\":\"OCT\"},{\"key\":\"osc3_semi\",\"label\":\"Semi\",\"short_name\":\"SEMI\"},{\"key"
    "\":\"osc3_detune\",\"label\":\"Detune\",\"short_name\":\"DTUNE\"},{\"key\":\"osc3_pulse_width\",\"label\":\"Pulse Widt"
    "h\",\"short_name\":\"PW\"},{\"key\":\"osc3_pwm\",\"label\":\"PWM\",\"short_name\":\"PWM\"},{\"key\":\"osc3_pwm_source\",\""
    "label\":\"PWM Source\",\"short_name\":\"PWSRC\"},{\"key\":\"osc3_key_track\",\"label\":\"Keytrack\"},{\"key\":\"osc3_b"
    "end_range\",\"label\":\"Bend\"},{\"key\":\"osc3_fm_source\",\"label\":\"FM Source\",\"short_name\":\"FMSRC\"},{\"key\":"
    "\"osc3_fm_amount\",\"label\":\"FM Amt\"}]},\"mixer\":{\"label\":\"Mixer\",\"children\":null,\"knobs\":[\"osc1_level\","
    "\"osc1_balance\",\"osc2_level\",\"osc2_balance\",\"osc3_level\",\"osc3_balance\",\"noise_level\",\"ringmod_level\""
    "],\"params\":[{\"key\":\"osc1_level\",\"label\":\"Osc 1 Level\",\"short_name\":\"O1LVL\"},{\"key\":\"osc1_balance\",\"l"
    "abel\":\"Osc 1 Balance\",\"short_name\":\"O1BAL\"},{\"key\":\"osc2_level\",\"label\":\"Osc 2 Level\",\"short_name\":\""
    "O2LVL\"},{\"key\":\"osc2_balance\",\"label\":\"Osc 2 Balance\",\"short_name\":\"O2BAL\"},{\"key\":\"osc3_level\",\"lab"
    "el\":\"Osc 3 Level\",\"short_name\":\"O3LVL\"},{\"key\":\"osc3_balance\",\"label\":\"Osc 3 Balance\",\"short_name\":\""
    "O3BAL\"},{\"key\":\"noise_level\",\"label\":\"Noise Level\",\"short_name\":\"NSLVL\"},{\"key\":\"ringmod_level\",\"lab"
    "el\":\"Ring Mod Level\",\"short_name\":\"RMLVL\"},{\"key\":\"noise_balance\",\"label\":\"Noise Balance\",\"short_nam"
    "e\":\"NSBAL\"},{\"key\":\"ringmod_balance\",\"label\":\"Ring Mod Balance\",\"short_name\":\"RMBAL\"},{\"key\":\"noise_"
    "mode_f1\",\"label\":\"Noise Mode F1\",\"short_name\":\"NMDF1\"},{\"key\":\"noise_mode_f2\",\"label\":\"Noise Mode F2"
    "\",\"short_name\":\"NMDF2\"}]},\"flt1\":{\"label\":\"Filter 1\",\"children\":null,\"knobs\":[\"flt1_type\",\"flt1_cuto"
    "ff\",\"flt1_resonance\",\"flt1_drive\",\"flt1_env_mod\",\"flt1_key_track\",\"flt1_vel_mod\",\"flt1_pan\"],\"params"
    "\":[{\"key\":\"flt1_type\",\"label\":\"Type\",\"short_name\":\"TYPE\"},{\"key\":\"flt1_cutoff\",\"label\":\"Cutoff\",\"sho"
    "rt_name\":\"CUT\"},{\"key\":\"flt1_resonance\",\"label\":\"Resonance\",\"short_name\":\"RES\"},{\"key\":\"flt1_drive\","
    "\"label\":\"Drive\",\"short_name\":\"DRIVE\"},{\"key\":\"flt1_env_mod\",\"label\":\"Env Amt\"},{\"key\":\"flt1_key_trac"
    "k\",\"label\":\"Keytrack\"},{\"key\":\"flt1_vel_mod\",\"label\":\"Velocity\"},{\"key\":\"flt1_pan\",\"label\":\"Pan\",\"sh"
    "ort_name\":\"PAN\"},{\"key\":\"flt1_mod_source\",\"label\":\"Mod Src\"},{\"key\":\"flt1_cutoff_mod\",\"label\":\"Cut M"
    "od\"},{\"key\":\"flt1_fm_source\",\"label\":\"FM Source\",\"short_name\":\"FMSRC\"},{\"key\":\"flt1_fm_amount\",\"labe"
    "l\":\"FM Amt\"},{\"key\":\"flt1_pan_mod_source\",\"label\":\"Pan Src\"},{\"key\":\"flt1_pan_mod\",\"label\":\"Pan Mod\""
    ",\"short_name\":\"PNMOD\"}]},\"flt2\":{\"label\":\"Filter 2\",\"children\":null,\"knobs\":[\"flt2_type\",\"flt2_cutof"
    "f\",\"flt2_resonance\",\"flt2_drive\",\"flt2_env_mod\",\"flt2_key_track\",\"flt2_vel_mod\",\"flt2_pan\"],\"params\""
    ":[{\"key\":\"flt2_type\",\"label\":\"Type\",\"short_name\":\"TYPE\"},{\"key\":\"flt2_cutoff\",\"label\":\"Cutoff\",\"shor"
    "t_name\":\"CUT\"},{\"key\":\"flt2_resonance\",\"label\":\"Resonance\",\"short_name\":\"RES\"},{\"key\":\"flt2_drive\",\""
    "label\":\"Drive\",\"short_name\":\"DRIVE\"},{\"key\":\"flt2_env_mod\",\"label\":\"Env Amt\"},{\"key\":\"flt2_key_track"
    "\",\"label\":\"Keytrack\"},{\"key\":\"flt2_vel_mod\",\"label\":\"Velocity\"},{\"key\":\"flt2_pan\",\"label\":\"Pan\",\"sho"
    "rt_name\":\"PAN\"},{\"key\":\"flt2_mod_source\",\"label\":\"Mod Src\"},{\"key\":\"flt2_cutoff_mod\",\"label\":\"Cut Mo"
    "d\"},{\"key\":\"flt2_fm_source\",\"label\":\"FM Source\",\"short_name\":\"FMSRC\"},{\"key\":\"flt2_fm_amount\",\"label"
    "\":\"FM Amt\"},{\"key\":\"flt2_pan_mod_source\",\"label\":\"Pan Src\"},{\"key\":\"flt2_pan_mod\",\"label\":\"Pan Mod\","
    "\"short_name\":\"PNMOD\"}]},\"amp\":{\"label\":\"Amplifier\",\"children\":null,\"knobs\":[\"amp_volume\",\"amp_veloci"
    "ty\",\"amp_mod_source\",\"amp_mod_amount\"],\"params\":[{\"key\":\"amp_volume\",\"label\":\"Volume\",\"short_name\":\""
    "VOL\"},{\"key\":\"amp_velocity\",\"label\":\"Velocity\",\"short_name\":\"VEL\"},{\"key\":\"amp_mod_source\",\"label\":\""
    "Mod Src\"},{\"key\":\"amp_mod_amount\",\"label\":\"Mod Amount\"}]},\"fenv\":{\"label\":\"Filter Env\",\"children\":nu"
    "ll,\"knobs\":[\"fenv_attack\",\"fenv_decay\",\"fenv_sustain\",\"fenv_release\",\"fenv_attack_level\",\"fenv_decay"
    "2\",\"fenv_sustain2\",\"fenv_mode\"],\"params\":[{\"key\":\"fenv_attack\",\"label\":\"Attack\",\"short_name\":\"ATK\"},"
    "{\"key\":\"fenv_decay\",\"label\":\"Decay\",\"short_name\":\"DEC\"},{\"key\":\"fenv_sustain\",\"label\":\"Sustain\",\"sho"
    "rt_name\":\"SUS\"},{\"key\":\"fenv_release\",\"label\":\"Release\",\"short_name\":\"REL\"},{\"key\":\"fenv_attack_leve"
    "l\",\"label\":\"Atk Level\"},{\"key\":\"fenv_decay2\",\"label\":\"Decay2\",\"short_name\":\"DEC2\"},{\"key\":\"fenv_sust"
    "ain2\",\"label\":\"Sustain2\",\"short_name\":\"SUS2\"},{\"key\":\"fenv_mode\",\"label\":\"Mode\",\"short_name\":\"MODE\"}"
    "]},\"aenv\":{\"label\":\"Amp Env\",\"children\":null,\"knobs\":[\"aenv_attack\",\"aenv_decay\",\"aenv_sustain\",\"aen"
    "v_release\",\"aenv_attack_level\",\"aenv_decay2\",\"aenv_sustain2\",\"aenv_mode\"],\"params\":[{\"key\":\"aenv_att"
    "ack\",\"label\":\"Attack\",\"short_name\":\"ATK\"},{\"key\":\"aenv_decay\",\"label\":\"Decay\",\"short_name\":\"DEC\"},{\""
    "key\":\"aenv_sustain\",\"label\":\"Sustain\",\"short_name\":\"SUS\"},{\"key\":\"aenv_release\",\"label\":\"Release\",\"s"
    "hort_name\":\"REL\"},{\"key\":\"aenv_attack_level\",\"label\":\"Atk Level\"},{\"key\":\"aenv_decay2\",\"label\":\"Deca"
    "y2\",\"short_name\":\"DEC2\"},{\"key\":\"aenv_sustain2\",\"label\":\"Sustain2\",\"short_name\":\"SUS2\"},{\"key\":\"aenv"
    "_mode\",\"label\":\"Mode\",\"short_name\":\"MODE\"}]},\"env3\":{\"label\":\"Env 3\",\"children\":null,\"knobs\":[\"env3_"
    "attack\",\"env3_decay\",\"env3_sustain\",\"env3_release\",\"env3_attack_level\",\"env3_decay2\",\"env3_sustain2\""
    ",\"env3_mode\"],\"params\":[{\"key\":\"env3_attack\",\"label\":\"Attack\",\"short_name\":\"ATK\"},{\"key\":\"env3_decay"
    "\",\"label\":\"Decay\",\"short_name\":\"DEC\"},{\"key\":\"env3_sustain\",\"label\":\"Sustain\",\"short_name\":\"SUS\"},{\""
    "key\":\"env3_release\",\"label\":\"Release\",\"short_name\":\"REL\"},{\"key\":\"env3_attack_level\",\"label\":\"Atk Le"
    "vel\"},{\"key\":\"env3_decay2\",\"label\":\"Decay2\",\"short_name\":\"DEC2\"},{\"key\":\"env3_sustain2\",\"label\":\"Sus"
    "tain2\",\"short_name\":\"SUS2\"},{\"key\":\"env3_mode\",\"label\":\"Mode\",\"short_name\":\"MODE\"}]},\"env4\":{\"label\""
    ":\"Env 4\",\"children\":null,\"knobs\":[\"env4_attack\",\"env4_decay\",\"env4_sustain\",\"env4_release\",\"env4_att"
    "ack_level\",\"env4_decay2\",\"env4_sustain2\",\"env4_mode\"],\"params\":[{\"key\":\"env4_attack\",\"label\":\"Attack"
    "\",\"short_name\":\"ATK\"},{\"key\":\"env4_decay\",\"label\":\"Decay\",\"short_name\":\"DEC\"},{\"key\":\"env4_sustain\","
    "\"label\":\"Sustain\",\"short_name\":\"SUS\"},{\"key\":\"env4_release\",\"label\":\"Release\",\"short_name\":\"REL\"},{\""
    "key\":\"env4_attack_level\",\"label\":\"Atk Level\"},{\"key\":\"env4_decay2\",\"label\":\"Decay2\",\"short_name\":\"DE"
    "C2\"},{\"key\":\"env4_sustain2\",\"label\":\"Sustain2\",\"short_name\":\"SUS2\"},{\"key\":\"env4_mode\",\"label\":\"Mode"
    "\",\"short_name\":\"MODE\"}]},\"lfo1\":{\"label\":\"LFO 1\",\"children\":null,\"knobs\":[\"lfo1_shape\",\"lfo1_speed\","
    "\"lfo1_speed_clocked\",\"lfo1_clocked\",\"lfo1_sync\",\"lfo1_start_phase\",\"lfo1_delay\",\"lfo1_fade\",\"lfo1_ke"
    "y_track\"],\"params\":[{\"key\":\"lfo1_shape\",\"label\":\"Shape\",\"short_name\":\"SHAPE\"},{\"key\":\"lfo1_speed\",\"l"
    "abel\":\"Speed\",\"short_name\":\"SPEED\"},{\"key\":\"lfo1_speed_clocked\",\"label\":\"Sync Speed\"},{\"key\":\"lfo1_c"
    "locked\",\"label\":\"Clocked\",\"short_name\":\"CLOCK\"},{\"key\":\"lfo1_sync\",\"label\":\"Sync\",\"short_name\":\"SYNC"
    "\"},{\"key\":\"lfo1_start_phase\",\"label\":\"Phase\"},{\"key\":\"lfo1_delay\",\"label\":\"Delay\",\"short_name\":\"DELA"
    "Y\"},{\"key\":\"lfo1_fade\",\"label\":\"Fade\",\"short_name\":\"FADE\"},{\"key\":\"lfo1_key_track\",\"label\":\"Keytrack"
    "\"}]},\"lfo2\":{\"label\":\"LFO 2\",\"children\":null,\"knobs\":[\"lfo2_shape\",\"lfo2_speed\",\"lfo2_speed_clocked\""
    ",\"lfo2_clocked\",\"lfo2_sync\",\"lfo2_start_phase\",\"lfo2_delay\",\"lfo2_fade\",\"lfo2_key_track\"],\"params\":["
    "{\"key\":\"lfo2_shape\",\"label\":\"Shape\",\"short_name\":\"SHAPE\"},{\"key\":\"lfo2_speed\",\"label\":\"Speed\",\"short"
    "_name\":\"SPEED\"},{\"key\":\"lfo2_speed_clocked\",\"label\":\"Sync Speed\"},{\"key\":\"lfo2_clocked\",\"label\":\"Clo"
    "cked\",\"short_name\":\"CLOCK\"},{\"key\":\"lfo2_sync\",\"label\":\"Sync\",\"short_name\":\"SYNC\"},{\"key\":\"lfo2_star"
    "t_phase\",\"label\":\"Phase\"},{\"key\":\"lfo2_delay\",\"label\":\"Delay\",\"short_name\":\"DELAY\"},{\"key\":\"lfo2_fad"
    "e\",\"label\":\"Fade\",\"short_name\":\"FADE\"},{\"key\":\"lfo2_key_track\",\"label\":\"Keytrack\"}]},\"lfo3\":{\"label\""
    ":\"LFO 3\",\"children\":null,\"knobs\":[\"lfo3_shape\",\"lfo3_speed\",\"lfo3_speed_clocked\",\"lfo3_clocked\",\"lfo"
    "3_sync\",\"lfo3_start_phase\",\"lfo3_delay\",\"lfo3_fade\",\"lfo3_key_track\"],\"params\":[{\"key\":\"lfo3_shape\","
    "\"label\":\"Shape\",\"short_name\":\"SHAPE\"},{\"key\":\"lfo3_speed\",\"label\":\"Speed\",\"short_name\":\"SPEED\"},{\"ke"
    "y\":\"lfo3_speed_clocked\",\"label\":\"Sync Speed\"},{\"key\":\"lfo3_clocked\",\"label\":\"Clocked\",\"short_name\":\""
    "CLOCK\"},{\"key\":\"lfo3_sync\",\"label\":\"Sync\",\"short_name\":\"SYNC\"},{\"key\":\"lfo3_start_phase\",\"label\":\"Ph"
    "ase\"},{\"key\":\"lfo3_delay\",\"label\":\"Delay\",\"short_name\":\"DELAY\"},{\"key\":\"lfo3_fade\",\"label\":\"Fade\",\"s"
    "hort_name\":\"FADE\"},{\"key\":\"lfo3_key_track\",\"label\":\"Keytrack\"}]},\"fmod1\":{\"label\":\"Fast Mod 1-2\",\"ch"
    "ildren\":null,\"knobs\":[\"fmod1_source\",\"fmod1_destination\",\"fmod1_amount\",\"fmod2_source\",\"fmod2_destin"
    "ation\",\"fmod2_amount\"],\"params\":[{\"key\":\"fmod1_source\",\"label\":\"F1 Src\",\"short_name\":\"F1SRC\"},{\"key\""
    ":\"fmod1_destination\",\"label\":\"F1 Dest\",\"short_name\":\"F1DST\"},{\"key\":\"fmod1_amount\",\"label\":\"F1 Amt\","
    "\"short_name\":\"F1AMT\"},{\"key\":\"fmod2_source\",\"label\":\"F2 Src\",\"short_name\":\"F2SRC\"},{\"key\":\"fmod2_des"
    "tination\",\"label\":\"F2 Dest\",\"short_name\":\"F2DST\"},{\"key\":\"fmod2_amount\",\"label\":\"F2 Amt\",\"short_name"
    "\":\"F2AMT\"}]},\"fmod3\":{\"label\":\"Fast Mod 3-4\",\"children\":null,\"knobs\":[\"fmod3_source\",\"fmod3_destinat"
    "ion\",\"fmod3_amount\",\"fmod4_source\",\"fmod4_destination\",\"fmod4_amount\"],\"params\":[{\"key\":\"fmod3_sourc"
    "e\",\"label\":\"F3 Src\",\"short_name\":\"F3SRC\"},{\"key\":\"fmod3_destination\",\"label\":\"F3 Dest\",\"short_name\":"
    "\"F3DST\"},{\"key\":\"fmod3_amount\",\"label\":\"F3 Amt\",\"short_name\":\"F3AMT\"},{\"key\":\"fmod4_source\",\"label\":"
    "\"F4 Src\",\"short_name\":\"F4SRC\"},{\"key\":\"fmod4_destination\",\"label\":\"F4 Dest\",\"short_name\":\"F4DST\"},{\""
    "key\":\"fmod4_amount\",\"label\":\"F4 Amt\",\"short_name\":\"F4AMT\"}]},\"smod1\":{\"label\":\"Mod Slot 1-2\",\"childr"
    "en\":null,\"knobs\":[\"smod1_source\",\"smod1_destination\",\"smod1_amount\",\"smod2_source\",\"smod2_destinatio"
    "n\",\"smod2_amount\"],\"params\":[{\"key\":\"smod1_source\",\"label\":\"M1 Src\",\"short_name\":\"M1SRC\"},{\"key\":\"sm"
    "od1_destination\",\"label\":\"M1 Dest\",\"short_name\":\"M1DST\"},{\"key\":\"smod1_amount\",\"label\":\"M1 Amt\",\"sho"
    "rt_name\":\"M1AMT\"},{\"key\":\"smod2_source\",\"label\":\"M2 Src\",\"short_name\":\"M2SRC\"},{\"key\":\"smod2_destina"
    "tion\",\"label\":\"M2 Dest\",\"short_name\":\"M2DST\"},{\"key\":\"smod2_amount\",\"label\":\"M2 Amt\",\"short_name\":\"M"
    "2AMT\"}]},\"smod3\":{\"label\":\"Mod Slot 3-4\",\"children\":null,\"knobs\":[\"smod3_source\",\"smod3_destination\""
    ",\"smod3_amount\",\"smod4_source\",\"smod4_destination\",\"smod4_amount\"],\"params\":[{\"key\":\"smod3_source\",\""
    "label\":\"M3 Src\",\"short_name\":\"M3SRC\"},{\"key\":\"smod3_destination\",\"label\":\"M3 Dest\",\"short_name\":\"M3D"
    "ST\"},{\"key\":\"smod3_amount\",\"label\":\"M3 Amt\",\"short_name\":\"M3AMT\"},{\"key\":\"smod4_source\",\"label\":\"M4 "
    "Src\",\"short_name\":\"M4SRC\"},{\"key\":\"smod4_destination\",\"label\":\"M4 Dest\",\"short_name\":\"M4DST\"},{\"key\""
    ":\"smod4_amount\",\"label\":\"M4 Amt\",\"short_name\":\"M4AMT\"}]},\"modif\":{\"label\":\"Modifiers\",\"children\":nul"
    "l,\"knobs\":[\"modif1_source1\",\"modif1_source2\",\"modif1_operator\",\"modif1_constant\",\"modif2_source1\",\"m"
    "odif2_source2\",\"modif2_operator\",\"modif2_constant\"],\"params\":[{\"key\":\"modif1_source1\",\"label\":\"M1 Sr"
    "c1\",\"short_name\":\"M1S1\"},{\"key\":\"modif1_source2\",\"label\":\"M1 Src2\",\"short_name\":\"M1S2\"},{\"key\":\"modi"
    "f1_operator\",\"label\":\"M1 Op\",\"short_name\":\"M1OP\"},{\"key\":\"modif1_constant\",\"label\":\"M1 Const\",\"short"
    "_name\":\"M1CN\"},{\"key\":\"modif2_source1\",\"label\":\"M2 Src1\",\"short_name\":\"M2S1\"},{\"key\":\"modif2_source2"
    "\",\"label\":\"M2 Src2\",\"short_name\":\"M2S2\"},{\"key\":\"modif2_operator\",\"label\":\"M2 Op\",\"short_name\":\"M2OP"
    "\"},{\"key\":\"modif2_constant\",\"label\":\"M2 Const\",\"short_name\":\"M2CN\"},{\"key\":\"modif3_source1\",\"label\":"
    "\"M3 Src1\",\"short_name\":\"M3S1\"},{\"key\":\"modif3_source2\",\"label\":\"M3 Src2\",\"short_name\":\"M3S2\"},{\"key\""
    ":\"modif3_operator\",\"label\":\"M3 Op\",\"short_name\":\"M3OP\"},{\"key\":\"modif3_constant\",\"label\":\"M3 Const\","
    "\"short_name\":\"M3CN\"},{\"key\":\"modif4_source1\",\"label\":\"M4 Src1\",\"short_name\":\"M4S1\"},{\"key\":\"modif4_s"
    "ource2\",\"label\":\"M4 Src2\",\"short_name\":\"M4S2\"},{\"key\":\"modif4_operator\",\"label\":\"M4 Op\",\"short_name\""
    ":\"M4OP\"},{\"key\":\"modif4_constant\",\"label\":\"M4 Const\",\"short_name\":\"M4CN\"}]},\"arp\":{\"label\":\"Arpeggia"
    "tor\",\"children\":null,\"knobs\":[\"arp_mode\",\"arp_pattern\",\"arp_clock\",\"arp_length\",\"arp_octave_range\",\""
    "arp_direction\",\"arp_sort_order\",\"arp_velo_mode\"],\"params\":[{\"key\":\"arp_mode\",\"label\":\"Mode\",\"short_n"
    "ame\":\"MODE\"},{\"key\":\"arp_pattern\",\"label\":\"Pattern\"},{\"key\":\"arp_clock\",\"label\":\"Clock\"},{\"key\":\"arp"
    "_length\",\"label\":\"Length\"},{\"key\":\"arp_octave_range\",\"label\":\"Octaves\"},{\"key\":\"arp_direction\",\"labe"
    "l\":\"Direction\"},{\"key\":\"arp_sort_order\",\"label\":\"Sort Order\"},{\"key\":\"arp_velo_mode\",\"label\":\"Veloci"
    "ty\"},{\"key\":\"arp_max_notes\",\"label\":\"Max Notes\"},{\"key\":\"arp_t_factor\",\"label\":\"Timing\"},{\"key\":\"arp"
    "_same_note_overlap\",\"label\":\"Overlap\"},{\"key\":\"arp_pattern_reset\",\"label\":\"Pat Reset\"},{\"key\":\"arp_p"
    "attern_length\",\"label\":\"Pat Length\"},{\"key\":\"tempo\",\"label\":\"Tempo\"}]},\"voice\":{\"label\":\"Voice\",\"chi"
    "ldren\":null,\"knobs\":[\"voice_mode\",\"unison_count\",\"unison_detune\",\"sync\",\"glide_mode\",\"glide_rate\",\"p"
    "itchmod_src\",\"pitchmod_amount\"],\"params\":[{\"key\":\"voice_mode\",\"label\":\"Voice Mode\",\"short_name\":\"VOI"
    "CE\"},{\"key\":\"unison_count\",\"label\":\"Count\"},{\"key\":\"unison_detune\",\"label\":\"Detune\",\"short_name\":\"DT"
    "UNE\"},{\"key\":\"sync\",\"label\":\"Sync\",\"short_name\":\"SYNC\"},{\"key\":\"glide_mode\",\"label\":\"Glide Mode\",\"sh"
    "ort_name\":\"GLIDE\"},{\"key\":\"glide_rate\",\"label\":\"Rate\"},{\"key\":\"pitchmod_src\",\"label\":\"Src\"},{\"key\":\""
    "pitchmod_amount\",\"label\":\"Amount\",\"short_name\":\"AMT\"}]},\"fx1\":{\"label\":\"FX 1\",\"children\":null,\"knobs"
    "\":[\"fx1_type\",\"fx1_mix\",\"fx1_chorus_delay\",\"fx1_chorus_depth\",\"fx1_chorus_speed\",\"fx1_flanger_depth\""
    ",\"fx1_flanger_feedback\",\"fx1_flanger_polarity\",\"fx1_flanger_speed\",\"fx1_phaser_center\",\"fx1_phaser_d"
    "epth\",\"fx1_phaser_feedback\",\"fx1_phaser_polarity\",\"fx1_phaser_spacing\",\"fx1_phaser_speed\",\"fx1_overd"
    "rive_cutoff\",\"fx1_overdrive_drive\",\"fx1_overdrive_post_gain\",\"fx1_vocoder_analysis_freq_high\",\"fx1_v"
    "ocoder_analysis_freq_low\",\"fx1_vocoder_analysis_signal\",\"fx1_vocoder_attack\",\"fx1_vocoder_bands\",\"fx"
    "1_vocoder_bandwidth\",\"fx1_vocoder_decay\",\"fx1_vocoder_eq_band_mid\",\"fx1_vocoder_eq_level_high\",\"fx1_"
    "vocoder_eq_level_low\",\"fx1_vocoder_eq_level_mid\",\"fx1_vocoder_offset_hi\",\"fx1_vocoder_offset_s\",\"fx1"
    "_vocoder_resonance\"],\"params\":[{\"key\":\"fx1_type\",\"label\":\"FX1 Type\",\"short_name\":\"TYPE\"},{\"key\":\"fx1"
    "_mix\",\"label\":\"FX1 Mix\",\"short_name\":\"MIX\"},{\"key\":\"fx1_chorus_delay\",\"label\":\"Chorus Delay\"},{\"key\""
    ":\"fx1_chorus_depth\",\"label\":\"Chorus Depth\"},{\"key\":\"fx1_chorus_speed\",\"label\":\"Chorus Speed\"},{\"key\""
    ":\"fx1_flanger_depth\",\"label\":\"Flanger Depth\"},{\"key\":\"fx1_flanger_feedback\",\"label\":\"Flanger Feedbac"
    "k\"},{\"key\":\"fx1_flanger_polarity\",\"label\":\"Flanger Polarity\"},{\"key\":\"fx1_flanger_speed\",\"label\":\"Fl"
    "anger Speed\"},{\"key\":\"fx1_phaser_center\",\"label\":\"Phaser Center\"},{\"key\":\"fx1_phaser_depth\",\"label\":"
    "\"Phaser Depth\"},{\"key\":\"fx1_phaser_feedback\",\"label\":\"Phaser Feedback\"},{\"key\":\"fx1_phaser_polarity\""
    ",\"label\":\"Phaser Polarity\"},{\"key\":\"fx1_phaser_spacing\",\"label\":\"Phaser Spacing\"},{\"key\":\"fx1_phaser"
    "_speed\",\"label\":\"Phaser Speed\"},{\"key\":\"fx1_overdrive_cutoff\",\"label\":\"Overdrive Cutoff\"},{\"key\":\"fx"
    "1_overdrive_drive\",\"label\":\"Overdrive Drive\"},{\"key\":\"fx1_overdrive_post_gain\",\"label\":\"Overdrive Po"
    "st Gain\"},{\"key\":\"fx1_vocoder_analysis_freq_high\",\"label\":\"Vocoder Analysis Freq High\"},{\"key\":\"fx1_"
    "vocoder_analysis_freq_low\",\"label\":\"Vocoder Analysis Freq Low\"},{\"key\":\"fx1_vocoder_analysis_signal\""
    ",\"label\":\"Vocoder Analysis Signal\"},{\"key\":\"fx1_vocoder_attack\",\"label\":\"Vocoder Attack\"},{\"key\":\"fx"
    "1_vocoder_bands\",\"label\":\"Vocoder Bands\"},{\"key\":\"fx1_vocoder_bandwidth\",\"label\":\"Vocoder Bandwidth\""
    "},{\"key\":\"fx1_vocoder_decay\",\"label\":\"Vocoder Decay\"},{\"key\":\"fx1_vocoder_eq_band_mid\",\"label\":\"Voco"
    "der EQ Band Mid\"},{\"key\":\"fx1_vocoder_eq_level_high\",\"label\":\"Vocoder EQ Level High\"},{\"key\":\"fx1_vo"
    "coder_eq_level_low\",\"label\":\"Vocoder EQ Level Low\"},{\"key\":\"fx1_vocoder_eq_level_mid\",\"label\":\"Vocod"
    "er EQ Level Mid\"},{\"key\":\"fx1_vocoder_offset_hi\",\"label\":\"Vocoder Offset Hi\"},{\"key\":\"fx1_vocoder_of"
    "fset_s\",\"label\":\"Vocoder Offset S\"},{\"key\":\"fx1_vocoder_resonance\",\"label\":\"Vocoder Resonance\"}]},\"f"
    "x2\":{\"label\":\"FX 2\",\"children\":null,\"knobs\":[\"fx2_type\",\"fx2_mix\",\"fx2_chorus_delay\",\"fx2_chorus_dep"
    "th\",\"fx2_chorus_speed\",\"fx2_flanger_depth\",\"fx2_flanger_feedback\",\"fx2_flanger_polarity\",\"fx2_flange"
    "r_speed\",\"fx2_phaser_center\",\"fx2_phaser_depth\",\"fx2_phaser_feedback\",\"fx2_phaser_polarity\",\"fx2_pha"
    "ser_spacing\",\"fx2_phaser_speed\",\"fx2_overdrive_cutoff\",\"fx2_overdrive_drive\",\"fx2_overdrive_post_gai"
    "n\",\"fx2_delay_autopan\",\"fx2_delay_cutoff\",\"fx2_delay_feedback\",\"fx2_delay_polarity\",\"fx2_reverb_damp"
    "ing\",\"fx2_reverb_decay\",\"fx2_reverb_diffusion\",\"fx2_reverb_highpass\",\"fx2_reverb_lowpass\",\"fx2_rever"
    "b_pre_delay\",\"fx2_reverb_shape\",\"fx2_reverb_size\",\"fx2_vocoder_analysis_freq_high\",\"fx2_vocoder_anal"
    "ysis_freq_low\",\"fx2_vocoder_analysis_signal\",\"fx2_vocoder_attack\",\"fx2_vocoder_bands\",\"fx2_vocoder_b"
    "andwidth\",\"fx2_vocoder_decay\",\"fx2_vocoder_eq_band_mid\",\"fx2_vocoder_eq_level_high\",\"fx2_vocoder_eq_"
    "level_low\",\"fx2_vocoder_eq_level_mid\",\"fx2_vocoder_offset_hi\",\"fx2_vocoder_offset_s\",\"fx2_vocoder_re"
    "sonance\"],\"params\":[{\"key\":\"fx2_type\",\"label\":\"FX2 Type\",\"short_name\":\"TYPE\"},{\"key\":\"fx2_mix\",\"labe"
    "l\":\"FX2 Mix\",\"short_name\":\"MIX\"},{\"key\":\"fx2_chorus_delay\",\"label\":\"Chorus Delay\"},{\"key\":\"fx2_choru"
    "s_depth\",\"label\":\"Chorus Depth\"},{\"key\":\"fx2_chorus_speed\",\"label\":\"Chorus Speed\"},{\"key\":\"fx2_flang"
    "er_depth\",\"label\":\"Flanger Depth\"},{\"key\":\"fx2_flanger_feedback\",\"label\":\"Flanger Feedback\"},{\"key\":"
    "\"fx2_flanger_polarity\",\"label\":\"Flanger Polarity\"},{\"key\":\"fx2_flanger_speed\",\"label\":\"Flanger Speed"
    "\"},{\"key\":\"fx2_phaser_center\",\"label\":\"Phaser Center\"},{\"key\":\"fx2_phaser_depth\",\"label\":\"Phaser Dep"
    "th\"},{\"key\":\"fx2_phaser_feedback\",\"label\":\"Phaser Feedback\"},{\"key\":\"fx2_phaser_polarity\",\"label\":\"P"
    "haser Polarity\"},{\"key\":\"fx2_phaser_spacing\",\"label\":\"Phaser Spacing\"},{\"key\":\"fx2_phaser_speed\",\"la"
    "bel\":\"Phaser Speed\"},{\"key\":\"fx2_overdrive_cutoff\",\"label\":\"Overdrive Cutoff\"},{\"key\":\"fx2_overdrive"
    "_drive\",\"label\":\"Overdrive Drive\"},{\"key\":\"fx2_overdrive_post_gain\",\"label\":\"Overdrive Post Gain\"},{"
    "\"key\":\"fx2_delay_autopan\",\"label\":\"Delay Autopan\"},{\"key\":\"fx2_delay_cutoff\",\"label\":\"Delay Cutoff\"}"
    ",{\"key\":\"fx2_delay_feedback\",\"label\":\"Delay Feedback\"},{\"key\":\"fx2_delay_polarity\",\"label\":\"Delay Po"
    "larity\"},{\"key\":\"fx2_reverb_damping\",\"label\":\"Reverb Damping\"},{\"key\":\"fx2_reverb_decay\",\"label\":\"Re"
    "verb Decay\"},{\"key\":\"fx2_reverb_diffusion\",\"label\":\"Reverb Diffusion\"},{\"key\":\"fx2_reverb_highpass\","
    "\"label\":\"Reverb Highpass\"},{\"key\":\"fx2_reverb_lowpass\",\"label\":\"Reverb Lowpass\"},{\"key\":\"fx2_reverb_"
    "pre_delay\",\"label\":\"Reverb Pre Delay\"},{\"key\":\"fx2_reverb_shape\",\"label\":\"Reverb Shape\"},{\"key\":\"fx2"
    "_reverb_size\",\"label\":\"Reverb Size\"},{\"key\":\"fx2_vocoder_analysis_freq_high\",\"label\":\"Vocoder Analys"
    "is Freq High\"},{\"key\":\"fx2_vocoder_analysis_freq_low\",\"label\":\"Vocoder Analysis Freq Low\"},{\"key\":\"f"
    "x2_vocoder_analysis_signal\",\"label\":\"Vocoder Analysis Signal\"},{\"key\":\"fx2_vocoder_attack\",\"label\":\""
    "Vocoder Attack\"},{\"key\":\"fx2_vocoder_bands\",\"label\":\"Vocoder Bands\"},{\"key\":\"fx2_vocoder_bandwidth\","
    "\"label\":\"Vocoder Bandwidth\"},{\"key\":\"fx2_vocoder_decay\",\"label\":\"Vocoder Decay\"},{\"key\":\"fx2_vocoder"
    "_eq_band_mid\",\"label\":\"Vocoder EQ Band Mid\"},{\"key\":\"fx2_vocoder_eq_level_high\",\"label\":\"Vocoder EQ "
    "Level High\"},{\"key\":\"fx2_vocoder_eq_level_low\",\"label\":\"Vocoder EQ Level Low\"},{\"key\":\"fx2_vocoder_e"
    "q_level_mid\",\"label\":\"Vocoder EQ Level Mid\"},{\"key\":\"fx2_vocoder_offset_hi\",\"label\":\"Vocoder Offset "
    "Hi\"},{\"key\":\"fx2_vocoder_offset_s\",\"label\":\"Vocoder Offset S\"},{\"key\":\"fx2_vocoder_resonance\",\"label"
    "\":\"Vocoder Resonance\"}]},\"settings\":{\"label\":\"Settings\",\"children\":null,\"knobs\":[\"dsp_clock\",\"gain\","
    "\"buffer_ms\"],\"params\":[{\"key\":\"preset\",\"label\":\"Preset\"},{\"key\":\"mode\",\"label\":\"Mode\"},{\"key\":\"part\""
    ",\"label\":\"Part\"},{\"key\":\"part_channel\",\"label\":\"Part Channel\"},{\"key\":\"part_volume\",\"label\":\"Part Vo"
    "lume\"},{\"key\":\"dsp_clock\",\"label\":\"DSP Clock\"},{\"key\":\"gain\",\"label\":\"Gain\"},{\"key\":\"buffer_ms\",\"lab"
    "el\":\"Buffer\"}]},\"root\":{\"label\":\"microQ\",\"children\":null,\"knobs\":[\"preset\",\"flt1_cutoff\",\"flt1_reson"
    "ance\",\"amp_volume\",\"fenv_attack\",\"fenv_decay\",\"fenv_sustain\",\"fenv_release\"],\"params\":[{\"key\":\"prese"
    "t\",\"label\":\"Preset\"},{\"level\":\"osc1\",\"label\":\"Osc 1\"},{\"level\":\"osc2\",\"label\":\"Osc 2\"},{\"level\":\"osc"
    "3\",\"label\":\"Osc 3\"},{\"level\":\"mixer\",\"label\":\"Mixer\"},{\"level\":\"flt1\",\"label\":\"Filter 1\"},{\"level\":\""
    "flt2\",\"label\":\"Filter 2\"},{\"level\":\"amp\",\"label\":\"Amplifier\"},{\"level\":\"fenv\",\"label\":\"Filter Env\"},"
    "{\"level\":\"aenv\",\"label\":\"Amp Env\"},{\"level\":\"env3\",\"label\":\"Env 3\"},{\"level\":\"env4\",\"label\":\"Env 4\"}"
    ",{\"level\":\"lfo1\",\"label\":\"LFO 1\"},{\"level\":\"lfo2\",\"label\":\"LFO 2\"},{\"level\":\"lfo3\",\"label\":\"LFO 3\"},"
    "{\"level\":\"fmod1\",\"label\":\"Fast Mod 1-2\"},{\"level\":\"fmod3\",\"label\":\"Fast Mod 3-4\"},{\"level\":\"smod1\",\""
    "label\":\"Mod Slot 1-2\"},{\"level\":\"smod3\",\"label\":\"Mod Slot 3-4\"},{\"level\":\"modif\",\"label\":\"Modifiers\""
    "},{\"level\":\"arp\",\"label\":\"Arpeggiator\"},{\"level\":\"voice\",\"label\":\"Voice\"},{\"level\":\"fx1\",\"label\":\"FX"
    " 1\"},{\"level\":\"fx2\",\"label\":\"FX 2\"},{\"level\":\"settings\",\"label\":\"Settings\"}]}}}";

}
