#!/usr/bin/env python3
"""Generate src/dsp/presets_os223.h from docs/presets-os223.tsv.

The names cannot be read from the ROM (they are not plain text in it) and
reading them from the running firmware costs a Program Change and an LCD
round trip EACH -- about two minutes for all 300. So they are dumped once by
tools/dump_presets.cpp, committed as the .tsv, and compiled in here: the
browser is then instant and nothing touches a file on the audio callback.

Run after re-dumping; tests/host compares this file against the .tsv by
content, so a stale header fails the build rather than shipping wrong names.
"""
import json, pathlib, re, sys

root = pathlib.Path(__file__).resolve().parent.parent
rows = []
for line in (root / "docs/presets-os223.tsv").read_text().splitlines():
    if line.startswith("#") or not line.strip():
        continue
    slot, name = line.split("\t", 1)
    rows.append((slot, name.rstrip()))

if len(rows) != 300:
    sys.exit(f"expected 300 presets, got {len(rows)}")

out = ["// GENERATED by tools/gen_presets_header.py from docs/presets-os223.tsv.",
       "// Do not edit; re-dump with tools/dump_presets.cpp and regenerate.",
       "#pragma once",
       "",
       "namespace vavra {",
       "// \"A1 LosAngeles2019\" ... \"C100 Moogish 2 DK\", in Program Change order.",
       "static const char* const g_presetNames[] = {"]
for slot, name in rows:
    # The device pads the 16-char field so the designer's initials sit right
    # aligned; collapse that for a menu row.
    label = re.sub(r"\s{2,}", " ", f"{slot} {name}").replace("\\", "").replace('"', "'")
    out.append(f'    "{label}",')
out += ["};", "}"]
(root / "src/dsp/presets_os223.h").write_text("\n".join(out) + "\n")

# module.json carries the same options: the chain host parses ITS copy for the
# param table while the shadow UI reads the plugin's chain_params, and the two
# disagreeing is how a module ends up with an invented knob writing a float
# into an enum. One generator, one source of truth.
module_path = root / "src/module.json"
module = json.loads(module_path.read_text())
labels = [re.sub(r"\s{2,}", " ", f"{slot} {name}") for slot, name in rows]
for param in module["chain_params"]:
    if param["key"] == "preset":
        param["options"] = labels
module_path.write_text(json.dumps(module, indent=4) + "\n")
print(f"wrote src/dsp/presets_os223.h and src/module.json with {len(rows)} presets")
